import type { SlimeColor, SlimeShopItem } from "./types";
import { SLIME_WEARABLE_CATALOG } from "./wearable-catalog";
import { SLIME_SHARED_ASSETS } from "./slime-assets";
import { slimeWearableEntry } from "./slime-wearables";
import {
  SLIME_ASSET_ROOT,
  SLIME_BALL_CATALOG,
  SLIME_COOKIE_PRICE,
  SLIME_DRINK_CATALOG,
  SLIME_SHOP_DEFAULT_PRICE,
  SLIME_SHOP_LOWER_TIER_EFFECT_BPS,
  SLIME_STATIC_FLOOR_CATALOG,
  SLIME_VEHICLE_CATALOG,
  SLIME_VEHICLE_DEFAULT_RISE_Y,
} from "./catalog-core";

export const SLIME_SHOP_CATALOG: readonly SlimeShopItem[] = [
  {
    key: "grass-floor-background",
    category: "background",
    floor: "grass-floor",
    labelKo: "잔디 바닥",
    price: SLIME_SHOP_DEFAULT_PRICE,
    effectKey: "walking_reward",
    effectBps: SLIME_SHOP_LOWER_TIER_EFFECT_BPS,
    spritePath: `${SLIME_ASSET_ROOT}/official/shared/grass-floor.png`,
  },
  ...SLIME_STATIC_FLOOR_CATALOG,
  {
    key: "shooting-star-night-sky-background",
    category: "background",
    floor: null,
    labelKo: "별똥별 밤하늘",
    price: SLIME_SHOP_DEFAULT_PRICE,
    effectKey: "assignment_reward",
    effectBps: SLIME_SHOP_LOWER_TIER_EFFECT_BPS,
    spritePath: `${SLIME_ASSET_ROOT}/shop/shooting-star-night-sky.gif`,
  },
  {
    key: "aurora-dream-sky-background",
    category: "background",
    floor: null,
    labelKo: "오로라의 꿈",
    price: 1_000,
    effectKey: "assignment_reward",
    effectBps: 300,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/aurora-dream-sky/aura-package/aurora-dream-sky-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/aurora-dream-sky/aura-package/aurora-dream-sky-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/aurora-dream-sky/static-background-64.png`,
  },
  {
    key: "cloud-garden-background",
    category: "background",
    floor: null,
    labelKo: "구름 정원",
    price: 700,
    effectKey: "walking_reward",
    effectBps: 200,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/cloud-garden/aura-package/cloud-garden-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/cloud-garden/aura-package/cloud-garden-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/cloud-garden/static-background-64.png`,
  },
  {
    key: "dreamy-toy-room-background",
    category: "background",
    floor: null,
    labelKo: "꿈꾸는 장난감",
    price: 500,
    effectKey: "assignment_reward",
    effectBps: 100,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/dreamy-toy-room/aura-package/dreamy-toy-room-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/dreamy-toy-room/aura-package/dreamy-toy-room-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/dreamy-toy-room/static-background-64.png`,
  },
  {
    key: "enchanted-forest-canopy-background",
    category: "background",
    floor: null,
    labelKo: "숲속의 마법",
    price: 500,
    effectKey: "reading_reward",
    effectBps: 100,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/enchanted-forest-canopy/aura-package/enchanted-forest-canopy-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/enchanted-forest-canopy/aura-package/enchanted-forest-canopy-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/enchanted-forest-canopy/static-background-64.png`,
  },
  {
    key: "fizzy-soda-dream-background",
    category: "background",
    floor: null,
    labelKo: "소다팝",
    price: 700,
    effectKey: "comment_reward",
    effectBps: 200,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/fizzy-soda-dream/aura-package/fizzy-soda-dream-6s-128.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/fizzy-soda-dream/aura-package/fizzy-soda-dream-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/fizzy-soda-dream/static-background-128.png`,
  },
  {
    key: "cherry-cloud-ume-background",
    category: "background",
    floor: null,
    labelKo: "봄날의 구름",
    price: 1_000,
    effectKey: "comment_reward",
    effectBps: 300,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/cherry-cloud-ume/aura-package/cherry-cloud-ume-6s-128.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/cherry-cloud-ume/aura-package/cherry-cloud-ume-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/cherry-cloud-ume/static-background-128.png`,
  },
  {
    key: "four-season-sky-background",
    category: "background",
    floor: null,
    labelKo: "포시즌스",
    price: 1_000,
    effectKey: "walking_reward",
    effectBps: 300,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/four-season-sky/aura-package/four-season-sky-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/four-season-sky/aura-package/four-season-sky-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/four-season-sky/static-background-64.png`,
  },
  {
    key: "jellyfish-ocean-background",
    category: "background",
    floor: null,
    labelKo: "해파리 유영",
    price: 1_000,
    effectKey: "reading_reward",
    effectBps: 300,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/jellyfish-ocean/aura-package/jellyfish-ocean-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/jellyfish-ocean/aura-package/jellyfish-ocean-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/jellyfish-ocean/static-background-64.png`,
  },
  {
    key: "lavender-butterfly-sky-background",
    category: "background",
    floor: null,
    labelKo: "라벤더 나비",
    price: 700,
    effectKey: "reading_reward",
    effectBps: 200,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/lavender-butterfly-sky/aura-package/lavender-butterfly-sky-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/lavender-butterfly-sky/aura-package/lavender-butterfly-sky-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/lavender-butterfly-sky/static-background-64.png`,
  },
  {
    key: "meteor-festival-sky-background",
    category: "background",
    floor: null,
    labelKo: "유성우",
    price: 700,
    effectKey: "walking_reward",
    effectBps: 200,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/meteor-festival-sky/aura-package/meteor-festival-sky-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/meteor-festival-sky/aura-package/meteor-festival-sky-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/meteor-festival-sky/static-background-64.png`,
  },
  {
    key: "midnight-snow-cloud-background",
    category: "background",
    floor: null,
    labelKo: "눈 내리는 밤",
    price: 700,
    effectKey: "assignment_reward",
    effectBps: 200,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/midnight-snow-cloud/aura-package/midnight-snow-cloud-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/midnight-snow-cloud/aura-package/midnight-snow-cloud-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/midnight-snow-cloud/static-background-64.png`,
  },
  {
    key: "moonlit-lake-background",
    category: "background",
    floor: null,
    labelKo: "달빛 호수",
    price: 700,
    effectKey: "reading_reward",
    effectBps: 200,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/moonlit-lake/aura-package/moonlit-lake-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/moonlit-lake/aura-package/moonlit-lake-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/moonlit-lake/static-background-64.png`,
  },
  {
    key: "mushroom-village-background",
    category: "background",
    floor: null,
    labelKo: "버섯 마을",
    price: 700,
    effectKey: "comment_reward",
    effectBps: 200,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/mushroom-village/aura-package/mushroom-village-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/mushroom-village/aura-package/mushroom-village-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/mushroom-village/static-background-64.png`,
  },
  {
    key: "neon-space-station-background",
    category: "background",
    floor: null,
    labelKo: "우주정거장",
    price: 700,
    effectKey: "assignment_reward",
    effectBps: 200,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/neon-space-station/aura-package/neon-space-station-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/neon-space-station/aura-package/neon-space-station-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/neon-space-station/static-background-64.png`,
  },
  {
    key: "rainy-window-cafe-background",
    category: "background",
    floor: null,
    labelKo: "비 오는 날",
    price: 500,
    effectKey: "comment_reward",
    effectBps: 100,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/rainy-window-cafe/aura-package/rainy-window-cafe-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/rainy-window-cafe/aura-package/rainy-window-cafe-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/rainy-window-cafe/static-background-64.png`,
  },
  {
    key: "starry-workshop-background",
    category: "background",
    floor: null,
    labelKo: "별빛 공방",
    price: 500,
    effectKey: "assignment_reward",
    effectBps: 100,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/starry-workshop/aura-package/starry-workshop-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/starry-workshop/aura-package/starry-workshop-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/starry-workshop/static-background-64.png`,
  },
  {
    key: "sunset-lantern-sky-background",
    category: "background",
    floor: null,
    labelKo: "노을 등불",
    price: 1_000,
    effectKey: "comment_reward",
    effectBps: 300,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/sunset-lantern-sky/aura-package/sunset-lantern-sky-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/sunset-lantern-sky/aura-package/sunset-lantern-sky-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/sunset-lantern-sky/static-background-64.png`,
  },
  {
    key: "tropical-fish-ocean-background",
    category: "background",
    floor: null,
    labelKo: "열대어 파티",
    price: 1_000,
    effectKey: "walking_reward",
    effectBps: 300,
    spritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/tropical-fish-ocean/aura-package/tropical-fish-ocean-6s-64.gif`,
    mobileSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/tropical-fish-ocean/aura-package/tropical-fish-ocean-6s-128.gif`,
    staticSpritePath: `${SLIME_ASSET_ROOT}/shop/backgrounds/tropical-fish-ocean/static-background-64.png`,
  },
  {
    key: "slime-blue-trampoline",
    category: "vehicle",
    floor: null,
    labelKo: "트램펄린",
    tier: 3,
    price: SLIME_SHOP_DEFAULT_PRICE,
    vehicleStance: "grounded",
    vehicleRiseY: SLIME_VEHICLE_DEFAULT_RISE_Y,
    effectKey: "walking_reward",
    effectBps: SLIME_SHOP_LOWER_TIER_EFFECT_BPS,
    spritePath: `${SLIME_ASSET_ROOT}/shop/slime-blue-trampoline.gif`,
  },
  ...SLIME_VEHICLE_CATALOG,
  ...SLIME_DRINK_CATALOG,
  ...SLIME_BALL_CATALOG,
  ...SLIME_WEARABLE_CATALOG.map((wearable): SlimeShopItem => ({
    key: wearable.key,
    category: "wearable",
    floor: null,
    labelKo: wearable.labelKo,
    price: wearable.price,
    spritePath: slimeWearableEntry(wearable.role, wearable.option)?.sheets.idle?.url ?? "",
    wearableRole: wearable.role,
    wearableOption: wearable.option,
    wearableAssetPath: `/api/slime-assets/wearables/${wearable.role}/${wearable.option}`,
    effectKey: wearable.effectKey,
    effectBps: wearable.effectBps,
  })),
  {
    key: "slime-cookie",
    category: "food",
    floor: null,
    labelKo: "쿠키",
    price: SLIME_COOKIE_PRICE,
    spritePath: SLIME_SHARED_ASSETS.cookie.imageUrl,
  },
] as const;

/** Accessory previews are intentionally local-only until a persistence API exists. */
