// Generated by scripts/import-slime-wearable-actions.mjs. Do not edit.

import { SLIME_WEB_WEARABLE_ACTION_REGISTRY_001 } from "./slime-wearable-actions.generated.chunks/wearable-actions-001.generated";
import { SLIME_WEB_WEARABLE_ACTION_REGISTRY_002 } from "./slime-wearable-actions.generated.chunks/wearable-actions-002.generated";

export const SLIME_WEB_WEARABLE_ACTION_REGISTRY = {
  ...SLIME_WEB_WEARABLE_ACTION_REGISTRY_001,
  ...SLIME_WEB_WEARABLE_ACTION_REGISTRY_002,
} as const;
