// Generated by scripts/import-slime-wearables.mjs. Do not edit by hand.

import { SLIME_WEB_WEARABLE_REGISTRY_001 } from "./slime-wearables.generated.chunks/wearables-001.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_002 } from "./slime-wearables.generated.chunks/wearables-002.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_003 } from "./slime-wearables.generated.chunks/wearables-003.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_004 } from "./slime-wearables.generated.chunks/wearables-004.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_005 } from "./slime-wearables.generated.chunks/wearables-005.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_006 } from "./slime-wearables.generated.chunks/wearables-006.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_007 } from "./slime-wearables.generated.chunks/wearables-007.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_008 } from "./slime-wearables.generated.chunks/wearables-008.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_009 } from "./slime-wearables.generated.chunks/wearables-009.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_010 } from "./slime-wearables.generated.chunks/wearables-010.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_011 } from "./slime-wearables.generated.chunks/wearables-011.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_012 } from "./slime-wearables.generated.chunks/wearables-012.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_013 } from "./slime-wearables.generated.chunks/wearables-013.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_014 } from "./slime-wearables.generated.chunks/wearables-014.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_015 } from "./slime-wearables.generated.chunks/wearables-015.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_016 } from "./slime-wearables.generated.chunks/wearables-016.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_017 } from "./slime-wearables.generated.chunks/wearables-017.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_018 } from "./slime-wearables.generated.chunks/wearables-018.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_019 } from "./slime-wearables.generated.chunks/wearables-019.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_020 } from "./slime-wearables.generated.chunks/wearables-020.generated";
import { SLIME_WEB_WEARABLE_REGISTRY_021 } from "./slime-wearables.generated.chunks/wearables-021.generated";

export const SLIME_WEB_WEARABLE_REGISTRY = {
  ...SLIME_WEB_WEARABLE_REGISTRY_001,
  ...SLIME_WEB_WEARABLE_REGISTRY_002,
  ...SLIME_WEB_WEARABLE_REGISTRY_003,
  ...SLIME_WEB_WEARABLE_REGISTRY_004,
  ...SLIME_WEB_WEARABLE_REGISTRY_005,
  ...SLIME_WEB_WEARABLE_REGISTRY_006,
  ...SLIME_WEB_WEARABLE_REGISTRY_007,
  ...SLIME_WEB_WEARABLE_REGISTRY_008,
  ...SLIME_WEB_WEARABLE_REGISTRY_009,
  ...SLIME_WEB_WEARABLE_REGISTRY_010,
  ...SLIME_WEB_WEARABLE_REGISTRY_011,
  ...SLIME_WEB_WEARABLE_REGISTRY_012,
  ...SLIME_WEB_WEARABLE_REGISTRY_013,
  ...SLIME_WEB_WEARABLE_REGISTRY_014,
  ...SLIME_WEB_WEARABLE_REGISTRY_015,
  ...SLIME_WEB_WEARABLE_REGISTRY_016,
  ...SLIME_WEB_WEARABLE_REGISTRY_017,
  ...SLIME_WEB_WEARABLE_REGISTRY_018,
  ...SLIME_WEB_WEARABLE_REGISTRY_019,
  ...SLIME_WEB_WEARABLE_REGISTRY_020,
  ...SLIME_WEB_WEARABLE_REGISTRY_021,
} as const;
export const SLIME_WEARABLE_LAYER_ORDER = ["slime","blush","eyewear","headwear","drink"] as const;
