"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Props = { boardId: string; initialShareMode: string; initialShareToken: string | null; initialShareShortCode?: string | null };
export function ShareTab({ boardId, initialShareMode, initialShareToken, initialShareShortCode }: Props) {
  const router = useRouter(); const [mode, setMode] = useState(initialShareMode); const [shareToken, setShareToken] = useState<string | null>(initialShareToken); const [shareShortCode, setShareShortCode] = useState<string | null>(initialShareShortCode ?? null); const [busy, setBusy] = useState(false); const [err, setErr] = useState<string | null>(null); const [svg, setSvg] = useState<string | null>(null); const [qrLoading, setQrLoading] = useState(false); const [shortCopied, setShortCopied] = useState(false);
  const isPublic = mode !== "private"; const shortUrl = isPublic && shareShortCode ? `${window.location.origin}/s/${shareShortCode}` : null;
  const loadQr = useCallback(async () => { if (!isPublic || !shareToken) { setSvg(null); return; } setQrLoading(true); try { const res = await fetch("/api/share/qr", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ boardId }) }); if (res.ok) { const j = await res.json(); setSvg(typeof j.svg === "string" ? j.svg : null); } else setSvg(null); } catch { setSvg(null); } finally { setQrLoading(false); } }, [boardId, mode, shareToken]);
  useEffect(() => { loadQr(); }, [loadQr]);
  const handleModeChange = async (nextMode: string) => { if (nextMode === mode) return; setBusy(true); setErr(null); try { const res = await fetch(`/api/boards/${boardId}/share`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mode: nextMode }) }); if (!res.ok) { const j = await res.json(); setErr(j.error === "forbidden" ? "권한이 없어요" : "저장에 실패했어요"); return; } const j = await res.json(); setMode(j.shareMode); setShareToken(j.shareToken); setShareShortCode(j.shareShortCode ?? null); router.refresh(); } catch { setErr("저장에 실패했어요"); } finally { setBusy(false); } };
  const handleRotate = async () => { setBusy(true); setErr(null); try { const res = await fetch(`/api/boards/${boardId}/share/rotate`, { method: "POST" }); if (!res.ok) { setErr("갱신에 실패했어요"); return; } const j = await res.json(); setShareToken(j.shareToken); setShareShortCode(j.shareShortCode ?? null); router.refresh(); setSvg(null); } catch { setErr("갱신에 실패했어요"); } finally { setBusy(false); } };
  const copyShortLink = async () => { if (!shortUrl) return; try { await navigator.clipboard.writeText(shortUrl); setShortCopied(true); setTimeout(() => setShortCopied(false), 2000); } catch { /* ignore */ } };
  return <div className="share-tab"><div className="share-mode-row"><label className="share-mode-label"><span style={{ fontSize: 14, fontWeight: 600 }}>공유</span><button type="button" className="share-mode-select" onClick={() => handleModeChange(isPublic ? "private" : "student")} disabled={busy}>{isPublic ? "학생 권한 공유 중" : "학생 권한으로 공유"}</button></label></div>{err && <p className="share-error">{err}</p>}{isPublic && shortUrl && <div className="share-qr-area"><div className="share-qr-wrap">{qrLoading && <span className="share-qr-loading">QR 생성 중…</span>}{!qrLoading && svg && <div className="share-qr-svg" dangerouslySetInnerHTML={{ __html: svg }} />}{!qrLoading && !svg && <span className="share-qr-loading">QR을 불러올 수 없어요</span>}</div><div className="share-link-row"><input type="text" className="share-link-input" value={shortUrl} readOnly aria-label="짧은 공유 링크" /><button type="button" className="share-copy-btn" onClick={copyShortLink}>{shortCopied ? "✓ 복사됨" : "복사"}</button></div><div className="share-actions"><button type="button" className="share-rotate-btn" onClick={handleRotate} disabled={busy}>🔄 새 링크 발급</button><button type="button" className="share-rotate-btn" onClick={() => handleModeChange("private")} disabled={busy}>공유 해제</button></div></div>}{mode === "private" && <div className="share-off-notice"><span aria-hidden="true" style={{ fontSize: 24 }}>🔒</span><p>이 보드는 비공개예요. 교사와 학생만 접근할 수 있어요.</p></div>}</div>;
}
