// Deterministic SLIME_MOBILE_ASSET_REGISTRY generated value chunk.

export const SLIME_GENERATED_CHUNK_000 = {
  "base/blue/idle": {
    ...{
      key: "base/blue/idle",
      evolution: "base",
      color: "blue",
      action: "idle",
      imageScale: 4,
      metadata: {
        frames: [
          {
            filename: "slime-blue-idle 0.aseprite",
            frame: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 240,
          },
          {
            filename: "slime-blue-idle 1.aseprite",
            frame: {
              x: 64,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 160,
          },
          {
            filename: "slime-blue-idle 2.aseprite",
            frame: {
              x: 128,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 180,
          },
          {
            filename: "slime-blue-idle 3.aseprite",
            frame: {
              x: 192,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 90,
          },
          {
            filename: "slime-blue-idle 4.aseprite",
            frame: {
              x: 256,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 90,
          },
          {
            filename: "slime-blue-idle 5.aseprite",
            frame: {
              x: 320,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 160,
          },
          {
            filename: "slime-blue-idle 6.aseprite",
            frame: {
              x: 384,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 180,
          },
          {
            filename: "slime-blue-idle 7.aseprite",
            frame: {
              x: 448,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 240,
          },
        ],
        meta: {
          app: "https://www.aseprite.org/",
          version: "1.x-dev",
          image: "slime-blue-idle-sheet.png",
          format: "RGBA8888",
          size: {
            w: 512,
            h: 64,
          },
          scale: "1",
          frameTags: [
            {
              name: "idle",
              from: 0,
              to: 7,
              direction: "forward",
              color: "#000000ff",
            },
          ],
          layers: [
            {
              name: "slime",
              opacity: 255,
              blendMode: "normal",
            },
          ],
        },
      },
    },
    sheet: require("../assets/slimes/base/blue/idle/sheet.png"),
  },
  "base/blue/happy": {
    ...{
      key: "base/blue/happy",
      evolution: "base",
      color: "blue",
      action: "happy",
      imageScale: 4,
      metadata: {
        frames: [
          {
            filename: "slime-blue-happy-heart 0.aseprite",
            frame: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 220,
          },
          {
            filename: "slime-blue-happy-heart 1.aseprite",
            frame: {
              x: 64,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 160,
          },
          {
            filename: "slime-blue-happy-heart 2.aseprite",
            frame: {
              x: 128,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 120,
          },
          {
            filename: "slime-blue-happy-heart 3.aseprite",
            frame: {
              x: 192,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 110,
          },
          {
            filename: "slime-blue-happy-heart 4.aseprite",
            frame: {
              x: 256,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 110,
          },
          {
            filename: "slime-blue-happy-heart 5.aseprite",
            frame: {
              x: 320,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 110,
          },
          {
            filename: "slime-blue-happy-heart 6.aseprite",
            frame: {
              x: 384,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 120,
          },
          {
            filename: "slime-blue-happy-heart 7.aseprite",
            frame: {
              x: 448,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 130,
          },
          {
            filename: "slime-blue-happy-heart 8.aseprite",
            frame: {
              x: 512,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 150,
          },
          {
            filename: "slime-blue-happy-heart 9.aseprite",
            frame: {
              x: 576,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 170,
          },
          {
            filename: "slime-blue-happy-heart 10.aseprite",
            frame: {
              x: 640,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 190,
          },
          {
            filename: "slime-blue-happy-heart 11.aseprite",
            frame: {
              x: 704,
              y: 0,
              w: 64,
              h: 64,
            },
            rotated: false,
            trimmed: false,
            spriteSourceSize: {
              x: 0,
              y: 0,
              w: 64,
              h: 64,
            },
            sourceSize: {
              w: 64,
              h: 64,
            },
            duration: 260,
          },
        ],
        meta: {
          app: "https://www.aseprite.org/",
          version: "1.x-dev",
          image: "slime-blue-happy-heart-sheet.png",
          format: "RGBA8888",
          size: {
            w: 768,
            h: 64,
          },
          scale: "1",
        },
      },
    },
    sheet: require("../assets/slimes/base/blue/happy/sheet.png"),
  },
} as const;
