import { StyleSheet } from "react-native";

/**
 * Shadow Alliance mirrors the standalone HTML game's visual language rather than
 * Aura's default board chrome. Keeping these values in the theme layer lets the
 * native student surface stay reference-accurate without leaking one-off design
 * literals into component code.
 */
export const shadowAllianceColors = {
  black: "#0a0a0c",
  panel: "#121217",
  line: "#2a2a33",
  gold: "#c9a24b",
  goldBright: "#e8c878",
  goldDim: "#7a6430",
  white: "#f4f1ea",
  muted: "#8a8a93",
  muted2: "#5c5c66",
  danger: "#e9a6a6",
  activeText: "#1a1407",
  peek: "#0e0e13",
  input: "#0d0d11",
  error: "#ffd0d0",
  blackShadow: "#000000",
  glowTop: "rgba(201,162,75,0.055)",
  glowBottom: "rgba(201,162,75,0.035)",
  glowMark: "rgba(201,162,75,0.025)",
  glowCard: "rgba(201,162,75,0.045)",
  commandShadow: "rgba(201,162,75,0.18)",
  gainShadow: "rgba(201,162,75,0.42)",
  errorBorder: "rgba(192,71,62,0.55)",
  errorBackground: "rgba(92,31,38,0.34)",
} as const;

const fonts = {
  bodyRegular: "NanumMyeongjo_400Regular",
  bodyBold: "NanumMyeongjo_700Bold",
  bodyExtraBold: "NanumMyeongjo_800ExtraBold",
  displayMedium: "Cinzel_500Medium",
  displayBold: "Cinzel_700Bold",
  displayBlack: "Cinzel_900Black",
  monoMedium: "JetBrainsMono_500Medium",
  monoBold: "JetBrainsMono_700Bold",
} as const;

const c = shadowAllianceColors;

export const shadowAllianceStyles = StyleSheet.create({
  screen: {
    position: "relative",
    flex: 1,
    overflow: "hidden",
    backgroundColor: c.black,
  },
  scroll: {
    flex: 1,
  },
  student: {
    width: "100%",
    maxWidth: 480,
    flexGrow: 1,
    alignSelf: "center",
    padding: 18,
    paddingBottom: 28,
  },
  centeredRoot: {
    width: "100%",
    maxWidth: 480,
    flex: 1,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: 24,
  },
  glowTop: {
    position: "absolute",
    top: -250,
    right: -250,
    width: 560,
    height: 420,
    borderRadius: 999,
    backgroundColor: c.glowTop,
  },
  glowBottom: {
    position: "absolute",
    bottom: -240,
    left: -260,
    width: 560,
    height: 420,
    borderRadius: 999,
    backgroundColor: c.glowBottom,
  },
  joinMark: {
    width: 90,
    height: 90,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    borderWidth: 1,
    borderColor: c.goldDim,
    borderRadius: 999,
    backgroundColor: c.glowMark,
  },
  joinMarkText: {
    color: c.goldBright,
    fontFamily: fonts.displayMedium,
    fontSize: 54,
    lineHeight: 62,
  },
  joinTitle: {
    color: c.goldBright,
    fontFamily: fonts.bodyExtraBold,
    fontSize: 22,
    letterSpacing: 5,
    textAlign: "center",
  },
  eyebrow: {
    color: c.gold,
    fontFamily: fonts.monoBold,
    fontSize: 11,
    letterSpacing: 4,
    textTransform: "uppercase",
    textAlign: "center",
  },
  notice: {
    marginTop: 14,
    color: c.muted,
    fontFamily: fonts.bodyRegular,
    fontSize: 12,
    lineHeight: 20,
    textAlign: "center",
  },
  revealRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  peek: {
    minWidth: 0,
    minHeight: 48,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    paddingHorizontal: 6,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: c.line,
    borderRadius: 10,
    backgroundColor: c.peek,
  },
  peekActive: {
    borderColor: c.goldBright,
    backgroundColor: c.gold,
    transform: [{ scale: 0.98 }],
  },
  peekText: {
    width: "100%",
    color: c.muted,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
    textAlign: "center",
  },
  peekTextActive: {
    color: c.activeText,
    fontFamily: fonts.bodyExtraBold,
  },
  card: {
    position: "relative",
    minHeight: 390,
    flexGrow: 1,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: c.line,
    borderRadius: 14,
    backgroundColor: c.panel,
    shadowColor: c.blackShadow,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.55,
    shadowRadius: 25,
    elevation: 14,
  },
  cardGlow: {
    position: "absolute",
    top: -95,
    right: -95,
    width: 220,
    height: 220,
    borderRadius: 999,
    backgroundColor: c.glowCard,
  },
  commandPanel: {
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 24,
  },
  centerPhase: {
    flex: 1,
    justifyContent: "center",
  },
  command: {
    marginTop: 10,
    color: c.goldBright,
    fontFamily: fonts.displayBlack,
    fontSize: 74,
    lineHeight: 80,
    textAlign: "center",
    textShadowColor: c.commandShadow,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 20,
  },
  commandSmall: {
    fontSize: 54,
    lineHeight: 62,
  },
  timerNotice: {
    marginTop: 8,
  },
  inputArea: {
    marginTop: "auto",
    gap: 14,
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 18,
  },
  form: {
    gap: 14,
  },
  inputLabel: {
    color: c.muted,
    fontFamily: fonts.bodyBold,
    fontSize: 12,
    textAlign: "center",
  },
  input: {
    width: "100%",
    minHeight: 80,
    borderWidth: 1,
    borderColor: c.line,
    borderRadius: 9,
    paddingHorizontal: 18,
    paddingVertical: 12,
    color: c.white,
    backgroundColor: c.input,
    fontFamily: fonts.monoBold,
    fontSize: 40,
    letterSpacing: 4,
    textAlign: "center",
  },
  actionButton: {
    width: "100%",
    minHeight: 52,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderWidth: 1,
    borderRadius: 10,
  },
  actionPrimary: {
    borderColor: c.goldBright,
    backgroundColor: c.gold,
  },
  actionGhost: {
    borderColor: c.line,
    backgroundColor: "transparent",
  },
  actionDisabled: {
    opacity: 0.4,
  },
  actionText: {
    fontFamily: fonts.bodyExtraBold,
    fontSize: 15,
    letterSpacing: 0.6,
    textAlign: "center",
  },
  actionPrimaryText: {
    color: c.activeText,
  },
  actionGhostText: {
    color: c.muted,
  },
  submittedPanel: {
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 30,
  },
  submittedBig: {
    marginBottom: 8,
    color: c.goldBright,
    fontFamily: fonts.displayBold,
    fontSize: 30,
    letterSpacing: 2,
    textAlign: "center",
  },
  submittedNumber: {
    color: c.goldBright,
    fontFamily: fonts.monoBold,
    fontSize: 18,
  },
  centerText: {
    textAlign: "center",
  },
  resultPanel: {
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 30,
  },
  gainPop: {
    marginTop: 8,
    color: c.goldBright,
    fontFamily: fonts.displayBlack,
    fontSize: 64,
    lineHeight: 74,
    textAlign: "center",
    textShadowColor: c.gainShadow,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 28,
  },
  rank: {
    fontSize: 54,
    lineHeight: 64,
  },
  resultNote: {
    marginTop: 18,
  },
  rule: {
    width: "100%",
    height: 1,
    marginVertical: 18,
    backgroundColor: c.goldDim,
    opacity: 0.72,
  },
  finalTeam: {
    marginTop: 8,
    color: c.goldBright,
    fontFamily: fonts.bodyBold,
    fontSize: 24,
    textAlign: "center",
  },
  errorText: {
    color: c.error,
    fontFamily: fonts.bodyRegular,
    fontSize: 13,
    lineHeight: 21,
    textAlign: "center",
  },
  errorBanner: {
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: c.errorBorder,
    borderRadius: 10,
    color: c.error,
    backgroundColor: c.errorBackground,
    fontFamily: fonts.bodyRegular,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
  connectionState: {
    marginTop: 10,
    color: c.muted2,
    fontFamily: fonts.monoMedium,
    fontSize: 10,
    textAlign: "center",
  },
  leaveButton: {
    minHeight: 44,
    alignSelf: "center",
    justifyContent: "center",
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderColor: "transparent",
    backgroundColor: "transparent",
  },
  leaveLabel: {
    color: c.danger,
    fontFamily: fonts.bodyBold,
    fontSize: 12,
  },
});
