// Generated by scripts/import-slime-wearables.mjs. Do not edit by hand.

export const SLIME_WEB_WEARABLE_REGISTRY_005 = {
  "eyewear/prism-kaleidoscope-glasses": {
    "key": "eyewear/prism-kaleidoscope-glasses",
    "role": "eyewear",
    "option": "prism-kaleidoscope-glasses",
    "published": true,
    "vendoredSource": false,
    "zIndex": 2,
    "colorSensitive": false,
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/prism-kaleidoscope-glasses/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/prism-kaleidoscope-glasses/happy/sheet.png"
      },
      "idle": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/prism-kaleidoscope-glasses/idle/sheet.png"
      },
      "trampoline": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/eyewear/prism-kaleidoscope-glasses/trampoline/sheet.png"
      },
      "water-puddle": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/eyewear/prism-kaleidoscope-glasses/water-puddle/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "drink:blue-ramune": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:grape-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:lemonade": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:melon-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:strawberry-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      },
      "idle": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      },
      "trampoline": {
        "sheet": "trampoline",
        "anchors": [
          {"sourceFrame":0,"dx":-1,"dy":17},
          {"sourceFrame":0,"dx":-1,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":-1,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":15},
          {"sourceFrame":0,"dx":0,"dy":16},
          {"sourceFrame":0,"dx":-2,"dy":21},
          {"sourceFrame":0,"dx":-2,"dy":22},
          {"sourceFrame":0,"dx":-1,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":7},
          {"sourceFrame":0,"dx":0,"dy":3},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":-2,"dy":-7},
          {"sourceFrame":0,"dx":-1,"dy":-14},
          {"sourceFrame":0,"dx":-1,"dy":-14},
          {"sourceFrame":0,"dx":-1,"dy":-10},
          {"sourceFrame":0,"dx":0,"dy":-5},
          {"sourceFrame":0,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":4,"dy":10},
          {"sourceFrame":0,"dx":-4,"dy":21},
          {"sourceFrame":0,"dx":-2,"dy":24},
          {"sourceFrame":0,"dx":-4,"dy":25},
          {"sourceFrame":0,"dx":4,"dy":29},
          {"sourceFrame":0,"dx":4,"dy":26},
          {"sourceFrame":0,"dx":2,"dy":21}
        ]
      },
      "water-puddle": {
        "sheet": "water-puddle",
        "anchors": [
          {"sourceFrame":0,"dx":-1,"dy":17},
          {"sourceFrame":0,"dx":-1,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":-1,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":15},
          {"sourceFrame":0,"dx":0,"dy":16},
          {"sourceFrame":0,"dx":-2,"dy":19},
          {"sourceFrame":0,"dx":-2,"dy":18},
          {"sourceFrame":0,"dx":-1,"dy":13},
          {"sourceFrame":0,"dx":0,"dy":9},
          {"sourceFrame":0,"dx":0,"dy":8},
          {"sourceFrame":0,"dx":0,"dy":6},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":-2,"dy":-7},
          {"sourceFrame":0,"dx":-1,"dy":-14},
          {"sourceFrame":0,"dx":-1,"dy":-14},
          {"sourceFrame":0,"dx":-1,"dy":-10},
          {"sourceFrame":0,"dx":0,"dy":-5},
          {"sourceFrame":0,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":4,"dy":10},
          {"sourceFrame":0,"dx":-4,"dy":18},
          {"sourceFrame":0,"dx":-2,"dy":19},
          {"sourceFrame":0,"dx":-4,"dy":20},
          {"sourceFrame":0,"dx":4,"dy":23},
          {"sourceFrame":0,"dx":4,"dy":22},
          {"sourceFrame":0,"dx":2,"dy":19}
        ]
      }
    }
  },
  "eyewear/red-sunglasses": {
    "key": "eyewear/red-sunglasses",
    "role": "eyewear",
    "option": "red-sunglasses",
    "published": true,
    "vendoredSource": false,
    "zIndex": 2,
    "colorSensitive": false,
    "sheets": {
      "idle": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/red-sunglasses/idle/sheet.png"
      },
      "trampoline": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/eyewear/red-sunglasses/trampoline/sheet.png"
      },
      "water-puddle": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/eyewear/red-sunglasses/water-puddle/sheet.png"
      }
    },
    "timelines": {
      "drink:blue-ramune": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:grape-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:lemonade": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:melon-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:strawberry-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "idle": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      },
      "trampoline": {
        "sheet": "trampoline",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0},
          {"sourceFrame":18,"dx":0,"dy":0},
          {"sourceFrame":19,"dx":0,"dy":0},
          {"sourceFrame":20,"dx":0,"dy":0},
          {"sourceFrame":21,"dx":0,"dy":0},
          {"sourceFrame":22,"dx":0,"dy":0},
          {"sourceFrame":23,"dx":0,"dy":0},
          {"sourceFrame":24,"dx":0,"dy":0},
          {"sourceFrame":25,"dx":0,"dy":0}
        ]
      },
      "water-puddle": {
        "sheet": "water-puddle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0},
          {"sourceFrame":18,"dx":0,"dy":0},
          {"sourceFrame":19,"dx":0,"dy":0},
          {"sourceFrame":20,"dx":0,"dy":0},
          {"sourceFrame":21,"dx":0,"dy":0},
          {"sourceFrame":22,"dx":0,"dy":0},
          {"sourceFrame":23,"dx":0,"dy":0},
          {"sourceFrame":24,"dx":0,"dy":0},
          {"sourceFrame":25,"dx":0,"dy":0}
        ]
      }
    }
  },
  "eyewear/red-wraparound-sport-shades": {
    "key": "eyewear/red-wraparound-sport-shades",
    "role": "eyewear",
    "option": "red-wraparound-sport-shades",
    "published": true,
    "vendoredSource": false,
    "zIndex": 2,
    "colorSensitive": false,
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/red-wraparound-sport-shades/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/red-wraparound-sport-shades/happy/sheet.png"
      },
      "idle": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/red-wraparound-sport-shades/idle/sheet.png"
      },
      "trampoline": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/eyewear/red-wraparound-sport-shades/trampoline/sheet.png"
      },
      "water-puddle": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/eyewear/red-wraparound-sport-shades/water-puddle/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "drink:blue-ramune": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:grape-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:lemonade": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:melon-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:strawberry-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      },
      "idle": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      },
      "trampoline": {
        "sheet": "trampoline",
        "anchors": [
          {"sourceFrame":0,"dx":-1,"dy":17},
          {"sourceFrame":0,"dx":-1,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":-1,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":15},
          {"sourceFrame":0,"dx":0,"dy":16},
          {"sourceFrame":0,"dx":-2,"dy":21},
          {"sourceFrame":0,"dx":-2,"dy":22},
          {"sourceFrame":0,"dx":-1,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":7},
          {"sourceFrame":0,"dx":0,"dy":3},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":-2,"dy":-7},
          {"sourceFrame":0,"dx":-1,"dy":-14},
          {"sourceFrame":0,"dx":-1,"dy":-14},
          {"sourceFrame":0,"dx":-1,"dy":-10},
          {"sourceFrame":0,"dx":0,"dy":-5},
          {"sourceFrame":0,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":4,"dy":10},
          {"sourceFrame":0,"dx":-4,"dy":21},
          {"sourceFrame":0,"dx":-2,"dy":24},
          {"sourceFrame":0,"dx":-4,"dy":25},
          {"sourceFrame":0,"dx":4,"dy":29},
          {"sourceFrame":0,"dx":4,"dy":26},
          {"sourceFrame":0,"dx":2,"dy":21}
        ]
      },
      "water-puddle": {
        "sheet": "water-puddle",
        "anchors": [
          {"sourceFrame":0,"dx":-1,"dy":17},
          {"sourceFrame":0,"dx":-1,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":-1,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":15},
          {"sourceFrame":0,"dx":0,"dy":16},
          {"sourceFrame":0,"dx":-2,"dy":19},
          {"sourceFrame":0,"dx":-2,"dy":18},
          {"sourceFrame":0,"dx":-1,"dy":13},
          {"sourceFrame":0,"dx":0,"dy":9},
          {"sourceFrame":0,"dx":0,"dy":8},
          {"sourceFrame":0,"dx":0,"dy":6},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":-2,"dy":-7},
          {"sourceFrame":0,"dx":-1,"dy":-14},
          {"sourceFrame":0,"dx":-1,"dy":-14},
          {"sourceFrame":0,"dx":-1,"dy":-10},
          {"sourceFrame":0,"dx":0,"dy":-5},
          {"sourceFrame":0,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":4,"dy":10},
          {"sourceFrame":0,"dx":-4,"dy":18},
          {"sourceFrame":0,"dx":-2,"dy":19},
          {"sourceFrame":0,"dx":-4,"dy":20},
          {"sourceFrame":0,"dx":4,"dy":23},
          {"sourceFrame":0,"dx":4,"dy":22},
          {"sourceFrame":0,"dx":2,"dy":19}
        ]
      }
    }
  },
} as const;
