// Generated by scripts/import-slime-wearables.mjs. Do not edit by hand.

export const SLIME_WEB_WEARABLE_REGISTRY_009 = {
  "headwear/brown-beanie": {
    "key": "headwear/brown-beanie",
    "role": "headwear",
    "option": "brown-beanie",
    "published": true,
    "vendoredSource": false,
    "zIndex": 3,
    "colorSensitive": false,
    "sheets": {
      "idle": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/brown-beanie/idle/sheet.png"
      },
      "trampoline": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/brown-beanie/trampoline/sheet.png"
      },
      "water-puddle": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/brown-beanie/water-puddle/sheet.png"
      }
    },
    "timelines": {
      "drink:blue-ramune": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:grape-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:lemonade": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:melon-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:strawberry-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "idle": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      },
      "trampoline": {
        "sheet": "trampoline",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0},
          {"sourceFrame":18,"dx":0,"dy":0},
          {"sourceFrame":19,"dx":0,"dy":0},
          {"sourceFrame":20,"dx":0,"dy":0},
          {"sourceFrame":21,"dx":0,"dy":0},
          {"sourceFrame":22,"dx":0,"dy":0},
          {"sourceFrame":23,"dx":0,"dy":0},
          {"sourceFrame":24,"dx":0,"dy":0},
          {"sourceFrame":25,"dx":0,"dy":0}
        ]
      },
      "water-puddle": {
        "sheet": "water-puddle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0},
          {"sourceFrame":18,"dx":0,"dy":0},
          {"sourceFrame":19,"dx":0,"dy":0},
          {"sourceFrame":20,"dx":0,"dy":0},
          {"sourceFrame":21,"dx":0,"dy":0},
          {"sourceFrame":22,"dx":0,"dy":0},
          {"sourceFrame":23,"dx":0,"dy":0},
          {"sourceFrame":24,"dx":0,"dy":0},
          {"sourceFrame":25,"dx":0,"dy":0}
        ]
      }
    }
  },
  "headwear/caramel-puppy-ear-headband": {
    "key": "headwear/caramel-puppy-ear-headband",
    "role": "headwear",
    "option": "caramel-puppy-ear-headband",
    "published": true,
    "vendoredSource": false,
    "zIndex": 3,
    "colorSensitive": false,
    "sheets": {
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/caramel-puppy-ear-headband/happy/sheet.png"
      },
      "idle": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/caramel-puppy-ear-headband/idle/sheet.png"
      },
      "trampoline": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/caramel-puppy-ear-headband/trampoline/sheet.png"
      },
      "water-puddle": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/caramel-puppy-ear-headband/water-puddle/sheet.png"
      }
    },
    "timelines": {
      "drink:blue-ramune": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:grape-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:lemonade": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:melon-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:strawberry-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      },
      "idle": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      },
      "trampoline": {
        "sheet": "trampoline",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0},
          {"sourceFrame":18,"dx":0,"dy":0},
          {"sourceFrame":19,"dx":0,"dy":0},
          {"sourceFrame":20,"dx":0,"dy":0},
          {"sourceFrame":21,"dx":0,"dy":0},
          {"sourceFrame":22,"dx":0,"dy":0},
          {"sourceFrame":23,"dx":0,"dy":0},
          {"sourceFrame":24,"dx":0,"dy":0},
          {"sourceFrame":25,"dx":0,"dy":0}
        ]
      },
      "water-puddle": {
        "sheet": "water-puddle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0},
          {"sourceFrame":18,"dx":0,"dy":0},
          {"sourceFrame":19,"dx":0,"dy":0},
          {"sourceFrame":20,"dx":0,"dy":0},
          {"sourceFrame":21,"dx":0,"dy":0},
          {"sourceFrame":22,"dx":0,"dy":0},
          {"sourceFrame":23,"dx":0,"dy":0},
          {"sourceFrame":24,"dx":0,"dy":0},
          {"sourceFrame":25,"dx":0,"dy":0}
        ]
      }
    }
  },
  "headwear/charcoal-beanie": {
    "key": "headwear/charcoal-beanie",
    "role": "headwear",
    "option": "charcoal-beanie",
    "published": true,
    "vendoredSource": false,
    "zIndex": 3,
    "colorSensitive": false,
    "sheets": {
      "idle": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/charcoal-beanie/idle/sheet.png"
      },
      "trampoline": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/charcoal-beanie/trampoline/sheet.png"
      },
      "water-puddle": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/charcoal-beanie/water-puddle/sheet.png"
      }
    },
    "timelines": {
      "drink:blue-ramune": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:grape-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:lemonade": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:melon-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:strawberry-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "idle": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      },
      "trampoline": {
        "sheet": "trampoline",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0},
          {"sourceFrame":18,"dx":0,"dy":0},
          {"sourceFrame":19,"dx":0,"dy":0},
          {"sourceFrame":20,"dx":0,"dy":0},
          {"sourceFrame":21,"dx":0,"dy":0},
          {"sourceFrame":22,"dx":0,"dy":0},
          {"sourceFrame":23,"dx":0,"dy":0},
          {"sourceFrame":24,"dx":0,"dy":0},
          {"sourceFrame":25,"dx":0,"dy":0}
        ]
      },
      "water-puddle": {
        "sheet": "water-puddle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0},
          {"sourceFrame":18,"dx":0,"dy":0},
          {"sourceFrame":19,"dx":0,"dy":0},
          {"sourceFrame":20,"dx":0,"dy":0},
          {"sourceFrame":21,"dx":0,"dy":0},
          {"sourceFrame":22,"dx":0,"dy":0},
          {"sourceFrame":23,"dx":0,"dy":0},
          {"sourceFrame":24,"dx":0,"dy":0},
          {"sourceFrame":25,"dx":0,"dy":0}
        ]
      }
    }
  },
} as const;
