// Generated by scripts/import-slime-wearables.mjs. Do not edit by hand.

export const SLIME_WEB_WEARABLE_REGISTRY_019 = {
  "headwear/silver-studio-headset": {
    "key": "headwear/silver-studio-headset",
    "role": "headwear",
    "option": "silver-studio-headset",
    "published": true,
    "vendoredSource": false,
    "zIndex": 3,
    "colorSensitive": false,
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/silver-studio-headset/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/silver-studio-headset/happy/sheet.png"
      },
      "idle": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/silver-studio-headset/idle/sheet.png"
      },
      "trampoline": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/silver-studio-headset/trampoline/sheet.png"
      },
      "water-puddle": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/silver-studio-headset/water-puddle/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "drink:blue-ramune": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:grape-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:lemonade": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:melon-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:strawberry-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      },
      "idle": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      },
      "trampoline": {
        "sheet": "trampoline",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":20},
          {"sourceFrame":0,"dx":0,"dy":21},
          {"sourceFrame":0,"dx":0,"dy":21},
          {"sourceFrame":0,"dx":0,"dy":15},
          {"sourceFrame":0,"dx":0,"dy":10},
          {"sourceFrame":0,"dx":0,"dy":6},
          {"sourceFrame":0,"dx":0,"dy":4},
          {"sourceFrame":0,"dx":0,"dy":-4},
          {"sourceFrame":0,"dx":0,"dy":-11},
          {"sourceFrame":0,"dx":0,"dy":-13},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-9},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":24},
          {"sourceFrame":0,"dx":0,"dy":29},
          {"sourceFrame":0,"dx":0,"dy":26},
          {"sourceFrame":0,"dx":0,"dy":20}
        ]
      },
      "water-puddle": {
        "sheet": "water-puddle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":18},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":11},
          {"sourceFrame":0,"dx":0,"dy":9},
          {"sourceFrame":0,"dx":0,"dy":4},
          {"sourceFrame":0,"dx":0,"dy":-4},
          {"sourceFrame":0,"dx":0,"dy":-11},
          {"sourceFrame":0,"dx":0,"dy":-13},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-9},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":9},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":19},
          {"sourceFrame":0,"dx":0,"dy":25},
          {"sourceFrame":0,"dx":0,"dy":22},
          {"sourceFrame":0,"dx":0,"dy":18}
        ]
      }
    }
  },
  "headwear/sprout-terrarium-dome-hat": {
    "key": "headwear/sprout-terrarium-dome-hat",
    "role": "headwear",
    "option": "sprout-terrarium-dome-hat",
    "published": true,
    "vendoredSource": false,
    "zIndex": 3,
    "colorSensitive": false,
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/sprout-terrarium-dome-hat/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/sprout-terrarium-dome-hat/happy/sheet.png"
      },
      "idle": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/sprout-terrarium-dome-hat/idle/sheet.png"
      },
      "trampoline": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/sprout-terrarium-dome-hat/trampoline/sheet.png"
      },
      "water-puddle": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/sprout-terrarium-dome-hat/water-puddle/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "drink:blue-ramune": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:grape-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:lemonade": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:melon-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:strawberry-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      },
      "idle": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      },
      "trampoline": {
        "sheet": "trampoline",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":20},
          {"sourceFrame":0,"dx":0,"dy":21},
          {"sourceFrame":0,"dx":0,"dy":21},
          {"sourceFrame":0,"dx":0,"dy":15},
          {"sourceFrame":0,"dx":0,"dy":10},
          {"sourceFrame":0,"dx":0,"dy":6},
          {"sourceFrame":0,"dx":0,"dy":4},
          {"sourceFrame":0,"dx":0,"dy":-4},
          {"sourceFrame":0,"dx":0,"dy":-11},
          {"sourceFrame":0,"dx":0,"dy":-13},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-9},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":24},
          {"sourceFrame":0,"dx":0,"dy":31},
          {"sourceFrame":0,"dx":0,"dy":26},
          {"sourceFrame":0,"dx":0,"dy":20}
        ]
      },
      "water-puddle": {
        "sheet": "water-puddle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":18},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":11},
          {"sourceFrame":0,"dx":0,"dy":9},
          {"sourceFrame":0,"dx":0,"dy":4},
          {"sourceFrame":0,"dx":0,"dy":-4},
          {"sourceFrame":0,"dx":0,"dy":-11},
          {"sourceFrame":0,"dx":0,"dy":-13},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-9},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":9},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":19},
          {"sourceFrame":0,"dx":0,"dy":25},
          {"sourceFrame":0,"dx":0,"dy":22},
          {"sourceFrame":0,"dx":0,"dy":18}
        ]
      }
    }
  },
  "headwear/starry-wizard-hat": {
    "key": "headwear/starry-wizard-hat",
    "role": "headwear",
    "option": "starry-wizard-hat",
    "published": true,
    "vendoredSource": false,
    "zIndex": 3,
    "colorSensitive": false,
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/starry-wizard-hat/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/starry-wizard-hat/happy/sheet.png"
      },
      "idle": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/starry-wizard-hat/idle/sheet.png"
      },
      "trampoline": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/starry-wizard-hat/trampoline/sheet.png"
      },
      "water-puddle": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/starry-wizard-hat/water-puddle/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "drink:blue-ramune": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:grape-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:lemonade": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:melon-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:strawberry-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      },
      "idle": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      },
      "trampoline": {
        "sheet": "trampoline",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":20},
          {"sourceFrame":0,"dx":0,"dy":21},
          {"sourceFrame":0,"dx":0,"dy":21},
          {"sourceFrame":0,"dx":0,"dy":15},
          {"sourceFrame":0,"dx":0,"dy":10},
          {"sourceFrame":0,"dx":0,"dy":6},
          {"sourceFrame":0,"dx":0,"dy":4},
          {"sourceFrame":0,"dx":0,"dy":-4},
          {"sourceFrame":0,"dx":0,"dy":-11},
          {"sourceFrame":0,"dx":0,"dy":-13},
          {"sourceFrame":0,"dx":0,"dy":-13},
          {"sourceFrame":0,"dx":0,"dy":-13},
          {"sourceFrame":0,"dx":0,"dy":-9},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":24},
          {"sourceFrame":0,"dx":0,"dy":31},
          {"sourceFrame":0,"dx":0,"dy":26},
          {"sourceFrame":0,"dx":0,"dy":20}
        ]
      },
      "water-puddle": {
        "sheet": "water-puddle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":18},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":11},
          {"sourceFrame":0,"dx":0,"dy":9},
          {"sourceFrame":0,"dx":0,"dy":4},
          {"sourceFrame":0,"dx":0,"dy":-4},
          {"sourceFrame":0,"dx":0,"dy":-11},
          {"sourceFrame":0,"dx":0,"dy":-13},
          {"sourceFrame":0,"dx":0,"dy":-13},
          {"sourceFrame":0,"dx":0,"dy":-13},
          {"sourceFrame":0,"dx":0,"dy":-9},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":9},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":19},
          {"sourceFrame":0,"dx":0,"dy":25},
          {"sourceFrame":0,"dx":0,"dy":22},
          {"sourceFrame":0,"dx":0,"dy":18}
        ]
      }
    }
  },
} as const;
