// Generated by scripts/import-slime-wearables.mjs. Do not edit by hand.

export const SLIME_WEB_WEARABLE_REGISTRY_011 = {
  "headwear/flame-tail-bandana": {
    "key": "headwear/flame-tail-bandana",
    "role": "headwear",
    "option": "flame-tail-bandana",
    "published": true,
    "vendoredSource": false,
    "zIndex": 3,
    "colorSensitive": false,
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/flame-tail-bandana/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/flame-tail-bandana/happy/sheet.png"
      },
      "idle": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/flame-tail-bandana/idle/sheet.png"
      },
      "trampoline": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/flame-tail-bandana/trampoline/sheet.png"
      },
      "water-puddle": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/flame-tail-bandana/water-puddle/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "drink:blue-ramune": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:grape-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:lemonade": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:melon-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:strawberry-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      },
      "idle": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      },
      "trampoline": {
        "sheet": "trampoline",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":20},
          {"sourceFrame":0,"dx":0,"dy":21},
          {"sourceFrame":0,"dx":0,"dy":21},
          {"sourceFrame":0,"dx":0,"dy":15},
          {"sourceFrame":0,"dx":0,"dy":10},
          {"sourceFrame":0,"dx":0,"dy":6},
          {"sourceFrame":0,"dx":0,"dy":4},
          {"sourceFrame":0,"dx":0,"dy":-4},
          {"sourceFrame":0,"dx":0,"dy":-11},
          {"sourceFrame":0,"dx":0,"dy":-13},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-9},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":24},
          {"sourceFrame":0,"dx":0,"dy":31},
          {"sourceFrame":0,"dx":0,"dy":26},
          {"sourceFrame":0,"dx":0,"dy":20}
        ]
      },
      "water-puddle": {
        "sheet": "water-puddle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":18},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":11},
          {"sourceFrame":0,"dx":0,"dy":9},
          {"sourceFrame":0,"dx":0,"dy":4},
          {"sourceFrame":0,"dx":0,"dy":-4},
          {"sourceFrame":0,"dx":0,"dy":-11},
          {"sourceFrame":0,"dx":0,"dy":-13},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-9},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":9},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":19},
          {"sourceFrame":0,"dx":0,"dy":25},
          {"sourceFrame":0,"dx":0,"dy":22},
          {"sourceFrame":0,"dx":0,"dy":18}
        ]
      }
    }
  },
  "headwear/forest-camo-bandana": {
    "key": "headwear/forest-camo-bandana",
    "role": "headwear",
    "option": "forest-camo-bandana",
    "published": true,
    "vendoredSource": false,
    "zIndex": 3,
    "colorSensitive": false,
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/forest-camo-bandana/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/forest-camo-bandana/happy/sheet.png"
      },
      "idle": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/forest-camo-bandana/idle/sheet.png"
      },
      "trampoline": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/forest-camo-bandana/trampoline/sheet.png"
      },
      "water-puddle": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/headwear/forest-camo-bandana/water-puddle/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "drink:blue-ramune": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:grape-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:lemonade": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:melon-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:strawberry-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      },
      "idle": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      },
      "trampoline": {
        "sheet": "trampoline",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":20},
          {"sourceFrame":0,"dx":0,"dy":21},
          {"sourceFrame":0,"dx":0,"dy":21},
          {"sourceFrame":0,"dx":0,"dy":15},
          {"sourceFrame":0,"dx":0,"dy":10},
          {"sourceFrame":0,"dx":0,"dy":6},
          {"sourceFrame":0,"dx":0,"dy":4},
          {"sourceFrame":0,"dx":0,"dy":-4},
          {"sourceFrame":0,"dx":0,"dy":-11},
          {"sourceFrame":0,"dx":0,"dy":-13},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-9},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":24},
          {"sourceFrame":0,"dx":0,"dy":31},
          {"sourceFrame":0,"dx":0,"dy":26},
          {"sourceFrame":0,"dx":0,"dy":20}
        ]
      },
      "water-puddle": {
        "sheet": "water-puddle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":18},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":17},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":11},
          {"sourceFrame":0,"dx":0,"dy":9},
          {"sourceFrame":0,"dx":0,"dy":4},
          {"sourceFrame":0,"dx":0,"dy":-4},
          {"sourceFrame":0,"dx":0,"dy":-11},
          {"sourceFrame":0,"dx":0,"dy":-13},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-15},
          {"sourceFrame":0,"dx":0,"dy":-9},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":9},
          {"sourceFrame":0,"dx":0,"dy":12},
          {"sourceFrame":0,"dx":0,"dy":19},
          {"sourceFrame":0,"dx":0,"dy":25},
          {"sourceFrame":0,"dx":0,"dy":22},
          {"sourceFrame":0,"dx":0,"dy":18}
        ]
      }
    }
  },
  "headwear/gold-crown-red-gem": {
    "key": "headwear/gold-crown-red-gem",
    "role": "headwear",
    "option": "gold-crown-red-gem",
    "published": false,
    "vendoredSource": true,
    "zIndex": 3,
    "colorSensitive": false,
    "sheets": {
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/gold-crown-red-gem/happy/sheet.png"
      },
      "idle": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/gold-crown-red-gem/idle/sheet.png"
      }
    },
    "timelines": {
      "drink:blue-ramune": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:grape-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:lemonade": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:melon-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:strawberry-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      },
      "idle": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
} as const;
