// Generated by scripts/import-slime-wearables.mjs. Do not edit by hand.

export const SLIME_WEB_WEARABLE_REGISTRY_001 = {
  "blush/peach-brush-blush": {
    "key": "blush/peach-brush-blush",
    "role": "blush",
    "option": "peach-brush-blush",
    "published": true,
    "vendoredSource": false,
    "zIndex": 1,
    "colorSensitive": false,
    "sheets": {
      "idle": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/blush/peach-brush-blush/idle/sheet.png"
      }
    },
    "timelines": {
      "drink:blue-ramune": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:grape-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:lemonade": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:melon-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:strawberry-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "idle": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "blush/rose-brush-blush": {
    "key": "blush/rose-brush-blush",
    "role": "blush",
    "option": "rose-brush-blush",
    "published": true,
    "vendoredSource": false,
    "zIndex": 1,
    "colorSensitive": false,
    "sheets": {
      "idle": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/blush/rose-brush-blush/idle/sheet.png"
      }
    },
    "timelines": {
      "drink:blue-ramune": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:grape-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:lemonade": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:melon-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:strawberry-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "idle": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "drink/blue-ramune": {
    "key": "drink/blue-ramune",
    "role": "drink",
    "option": "blue-ramune",
    "published": true,
    "vendoredSource": false,
    "zIndex": 4,
    "colorSensitive": true,
    "sheets": {
      "drink-blue-ramune": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "urlByColor": {
          "blue": "/creatures/slimes/official/composition/drink/blue-ramune/drink-blue-ramune/blue/sheet.png",
          "green": "/creatures/slimes/official/composition/drink/blue-ramune/drink-blue-ramune/green/sheet.png",
          "purple": "/creatures/slimes/official/composition/drink/blue-ramune/drink-blue-ramune/purple/sheet.png",
          "red": "/creatures/slimes/official/composition/drink/blue-ramune/drink-blue-ramune/red/sheet.png",
          "yellow": "/creatures/slimes/official/composition/drink/blue-ramune/drink-blue-ramune/yellow/sheet.png"
        }
      }
    },
    "timelines": {
      "drink:blue-ramune": {
        "sheet": "drink-blue-ramune",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "drink/grape-soda": {
    "key": "drink/grape-soda",
    "role": "drink",
    "option": "grape-soda",
    "published": true,
    "vendoredSource": false,
    "zIndex": 4,
    "colorSensitive": true,
    "sheets": {
      "drink-grape-soda": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "urlByColor": {
          "blue": "/creatures/slimes/official/composition/drink/grape-soda/drink-grape-soda/blue/sheet.png",
          "green": "/creatures/slimes/official/composition/drink/grape-soda/drink-grape-soda/green/sheet.png",
          "purple": "/creatures/slimes/official/composition/drink/grape-soda/drink-grape-soda/purple/sheet.png",
          "red": "/creatures/slimes/official/composition/drink/grape-soda/drink-grape-soda/red/sheet.png",
          "yellow": "/creatures/slimes/official/composition/drink/grape-soda/drink-grape-soda/yellow/sheet.png"
        }
      }
    },
    "timelines": {
      "drink:grape-soda": {
        "sheet": "drink-grape-soda",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "drink/lemonade": {
    "key": "drink/lemonade",
    "role": "drink",
    "option": "lemonade",
    "published": true,
    "vendoredSource": false,
    "zIndex": 4,
    "colorSensitive": true,
    "sheets": {
      "drink-lemonade": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "urlByColor": {
          "blue": "/creatures/slimes/official/composition/drink/lemonade/drink-lemonade/blue/sheet.png",
          "green": "/creatures/slimes/official/composition/drink/lemonade/drink-lemonade/green/sheet.png",
          "purple": "/creatures/slimes/official/composition/drink/lemonade/drink-lemonade/purple/sheet.png",
          "red": "/creatures/slimes/official/composition/drink/lemonade/drink-lemonade/red/sheet.png",
          "yellow": "/creatures/slimes/official/composition/drink/lemonade/drink-lemonade/yellow/sheet.png"
        }
      }
    },
    "timelines": {
      "drink:lemonade": {
        "sheet": "drink-lemonade",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "drink/melon-soda": {
    "key": "drink/melon-soda",
    "role": "drink",
    "option": "melon-soda",
    "published": true,
    "vendoredSource": false,
    "zIndex": 4,
    "colorSensitive": true,
    "sheets": {
      "drink-melon-soda": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "urlByColor": {
          "blue": "/creatures/slimes/official/composition/drink/melon-soda/drink-melon-soda/blue/sheet.png",
          "green": "/creatures/slimes/official/composition/drink/melon-soda/drink-melon-soda/green/sheet.png",
          "purple": "/creatures/slimes/official/composition/drink/melon-soda/drink-melon-soda/purple/sheet.png",
          "red": "/creatures/slimes/official/composition/drink/melon-soda/drink-melon-soda/red/sheet.png",
          "yellow": "/creatures/slimes/official/composition/drink/melon-soda/drink-melon-soda/yellow/sheet.png"
        }
      }
    },
    "timelines": {
      "drink:melon-soda": {
        "sheet": "drink-melon-soda",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "drink/strawberry-soda": {
    "key": "drink/strawberry-soda",
    "role": "drink",
    "option": "strawberry-soda",
    "published": true,
    "vendoredSource": false,
    "zIndex": 4,
    "colorSensitive": true,
    "sheets": {
      "drink-strawberry-soda": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "urlByColor": {
          "blue": "/creatures/slimes/official/composition/drink/strawberry-soda/drink-strawberry-soda/blue/sheet.png",
          "green": "/creatures/slimes/official/composition/drink/strawberry-soda/drink-strawberry-soda/green/sheet.png",
          "purple": "/creatures/slimes/official/composition/drink/strawberry-soda/drink-strawberry-soda/purple/sheet.png",
          "red": "/creatures/slimes/official/composition/drink/strawberry-soda/drink-strawberry-soda/red/sheet.png",
          "yellow": "/creatures/slimes/official/composition/drink/strawberry-soda/drink-strawberry-soda/yellow/sheet.png"
        }
      }
    },
    "timelines": {
      "drink:strawberry-soda": {
        "sheet": "drink-strawberry-soda",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "eyewear/black-goggles": {
    "key": "eyewear/black-goggles",
    "role": "eyewear",
    "option": "black-goggles",
    "published": true,
    "vendoredSource": false,
    "zIndex": 2,
    "colorSensitive": false,
    "sheets": {
      "idle": {
        "frameCount": 8,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/black-goggles/idle/sheet.png"
      },
      "trampoline": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/eyewear/black-goggles/trampoline/sheet.png"
      },
      "water-puddle": {
        "frameCount": 26,
        "frameSize": {"w":64,"h":81},
        "characterOffsetY": 17,
        "grounded": false,
        "url": "/creatures/slimes/official/composition/eyewear/black-goggles/water-puddle/sheet.png"
      }
    },
    "timelines": {
      "drink:blue-ramune": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:grape-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:lemonade": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:melon-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "drink:strawberry-soda": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":3,"dx":0,"dy":-1},
          {"sourceFrame":4,"dx":0,"dy":-1},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":-2},
          {"sourceFrame":0,"dx":0,"dy":0}
        ]
      },
      "idle": {
        "sheet": "idle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0}
        ]
      },
      "trampoline": {
        "sheet": "trampoline",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0},
          {"sourceFrame":18,"dx":0,"dy":0},
          {"sourceFrame":19,"dx":0,"dy":0},
          {"sourceFrame":20,"dx":0,"dy":0},
          {"sourceFrame":21,"dx":0,"dy":0},
          {"sourceFrame":22,"dx":0,"dy":0},
          {"sourceFrame":23,"dx":0,"dy":0},
          {"sourceFrame":24,"dx":0,"dy":0},
          {"sourceFrame":25,"dx":0,"dy":0}
        ]
      },
      "water-puddle": {
        "sheet": "water-puddle",
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0},
          {"sourceFrame":18,"dx":0,"dy":0},
          {"sourceFrame":19,"dx":0,"dy":0},
          {"sourceFrame":20,"dx":0,"dy":0},
          {"sourceFrame":21,"dx":0,"dy":0},
          {"sourceFrame":22,"dx":0,"dy":0},
          {"sourceFrame":23,"dx":0,"dy":0},
          {"sourceFrame":24,"dx":0,"dy":0},
          {"sourceFrame":25,"dx":0,"dy":0}
        ]
      }
    }
  },
} as const;
