import { StyleSheet } from "react-native";
import { borders } from "../../theme/tokens";
import { colors } from "../../theme/tokens";
import { composer } from "../../theme/tokens";
import { controls } from "../../theme/tokens";
import { pageChrome } from "../../theme/tokens";
import { radii } from "../../theme/tokens";
import { spacing } from "../../theme/tokens";
import { tapMin } from "../../theme/tokens";
import { typography } from "../../theme/tokens";
import { walking } from "../../theme/tokens";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  keyboardWrap: { flex: 1 },
  pageTabs: { paddingHorizontal: pageChrome.horizontalPadding },
  content: {
    flexGrow: 1,
    paddingHorizontal: pageChrome.horizontalPadding,
    paddingTop: pageChrome.contentStartGap,
    paddingBottom: spacing.xxxl + spacing.xxl,
    gap: spacing.lg,
  },
  contentLandscape: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.xxl,
    paddingHorizontal: spacing.xxl,
  },
  tabContent: {
    width: "100%",
    minWidth: 0,
    gap: spacing.lg,
  },
  summarySection: { gap: spacing.sm },
  summaryRows: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: spacing.sm,
  },
  summaryRow: {
    flex: 1,
    minHeight: tapMin,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    paddingVertical: spacing.sm,
  },
  summaryLabel: {
    ...typography.label,
    color: colors.textMuted,
    textAlign: "center",
  },
  summaryValue: {
    ...typography.section,
    color: colors.text,
    textAlign: "center",
  },
  composerSheet: {
    width: "100%",
    maxWidth: composer.sheetMaxWidth,
    maxHeight: composer.sheetMaxHeight,
  },
  composerContent: {
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.lg,
    gap: spacing.lg,
  },
  composerScroll: { flexShrink: 1 },
  composerFooter: {
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.xl,
  },
  composerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xs,
  },
  composerClose: {
    width: controls.closeButton,
    minHeight: tapMin,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: borders.none,
    borderColor: colors.transparent,
    borderRadius: radii.none,
    backgroundColor: colors.transparent,
  },
  historyColumn: { gap: spacing.md, minWidth: 0 },
  landscapeHistoryColumn: { flex: 2, minWidth: 0 },
  missionScreen: { gap: spacing.xxl },
  missionSection: { gap: spacing.md },
  missionBlock: { gap: spacing.md },
  rewardClaimButton: {
    width: "100%",
    maxWidth: walking.rewardClaimButtonWidth,
    minHeight: tapMin,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  rewardClaimButtonImage: {
    width: "100%",
    height: tapMin,
  },
  rewardClaimedLabel: {
    ...typography.micro,
    color: colors.accentTintedText,
    textAlign: "center",
  },
  missionError: { gap: spacing.sm, paddingVertical: spacing.md },
  missionPreviewList: {},
  missionPreview: {
    minHeight: tapMin,
    paddingVertical: spacing.md,
  },
  missionPreviewText: { flex: 1, minWidth: 0, gap: spacing.xxs },
  missionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  missionPreviewTitle: { ...typography.section, color: colors.text },
  missionPreviewDescription: { ...typography.body, color: colors.textMuted },
  missionProgressLabel: { ...typography.badge, color: colors.accentTintedText },
  missionProgressComplete: { color: colors.statusReviewedText },
  readingMilestones: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.xxs,
  },
  readingMilestone: {
    flex: 1,
    minWidth: 0,
    alignItems: "center",
    gap: spacing.xxs,
  },
  readingMilestoneLabel: {
    ...typography.micro,
    color: colors.textMuted,
    textAlign: "center",
  },
  rewardCoinAmount: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xxs,
  },
  rewardCoinImage: {
    width: walking.rankRewardCoinSize,
    height: walking.rankRewardCoinSize,
  },
  rewardCoinText: {
    ...typography.micro,
    color: colors.text,
  },
  fieldGroup: { gap: spacing.xs },
  fieldLabel: { ...typography.label, color: colors.textMuted },
  reflectionInput: {
    minHeight: Math.max(controls.multilineInputMinHeight * 2.4, 230),
    textAlignVertical: "top",
  },
  error: { ...typography.body, color: colors.danger },
  notice: { ...typography.body, color: colors.statusReviewedText },
  historyTypeNavItem: { minWidth: 84, alignItems: "center" },
  loadingState: {
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.xl,
  },
  muted: { ...typography.body, color: colors.textMuted },
  emptyTypeEntry: {
    ...typography.body,
    color: colors.textFaint,
    paddingVertical: spacing.md,
  },
  emptyState: {
    paddingVertical: spacing.xl,
    gap: spacing.xs,
    borderBottomWidth: borders.hairline,
    borderBottomColor: colors.border,
  },
  emptyTitle: { ...typography.section, color: colors.text },
  emptyDescription: { ...typography.body, color: colors.textMuted },
  entry: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: spacing.sm,
  },
  entryIndex: {
    width: borders.medium,
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
  },
  entryContent: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
    borderRadius: radii.btn,
  },
  entryExpanded: {
    padding: spacing.sm,
    backgroundColor: colors.surfaceAlt,
  },
  entryToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    borderWidth: borders.none,
    borderColor: colors.transparent,
    borderRadius: radii.none,
    backgroundColor: colors.transparent,
  },
  entryTopline: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  entryType: { ...typography.badge, color: colors.accentTintedText },
  entryDate: { ...typography.micro, color: colors.textMuted },
  entryTitle: { ...typography.section, color: colors.text, flex: 1 },
  entryDetails: { gap: spacing.sm },
  meta: { ...typography.micro, color: colors.textMuted },
  body: { ...typography.body, color: colors.text },
  feedbackRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    paddingTop: spacing.md,
    borderTopWidth: borders.hairline,
    borderTopColor: colors.border,
  },
  feedbackScore: { ...typography.label, color: colors.accentTintedText },
  feedback: { ...typography.body, color: colors.accentTintedText, flex: 1 },
  feedbackStatusBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingTop: spacing.md,
    borderTopWidth: borders.hairline,
    borderTopColor: colors.border,
  },
  feedbackStatusText: { ...typography.body, color: colors.textMuted, flex: 1 },
  feedbackRetry: {
    minHeight: tapMin,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderWidth: borders.hairline,
    borderColor: colors.border,
    borderRadius: radii.pill,
    backgroundColor: colors.surface,
  },
  feedbackRetryText: { ...typography.label, color: colors.accent },
});
