// Generated by scripts/import-slime-wearable-actions.mjs. Do not edit.

export const SLIME_WEB_WEARABLE_ACTION_REGISTRY_001 = {
  "blush/peach-brush-blush": {
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/blush/peach-brush-blush/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/blush/peach-brush-blush/happy/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "frameCount": 18,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "frameCount": 12,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      }
    }
  },
  "blush/rose-brush-blush": {
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/blush/rose-brush-blush/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/blush/rose-brush-blush/happy/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "frameCount": 18,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "frameCount": 12,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      }
    }
  },
  "eyewear/black-goggles": {
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/black-goggles/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/black-goggles/happy/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "frameCount": 18,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "frameCount": 12,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      }
    }
  },
  "eyewear/black-sunglasses": {
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/black-sunglasses/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/black-sunglasses/happy/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "frameCount": 18,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "frameCount": 12,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      }
    }
  },
  "eyewear/copper-goggles": {
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/copper-goggles/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/copper-goggles/happy/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "frameCount": 18,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "frameCount": 12,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      }
    }
  },
  "eyewear/gold-goggles": {
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/gold-goggles/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/gold-goggles/happy/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "frameCount": 18,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "frameCount": 12,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      }
    }
  },
  "eyewear/red-sunglasses": {
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/red-sunglasses/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/red-sunglasses/happy/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "frameCount": 18,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "frameCount": 12,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      }
    }
  },
  "eyewear/round-glasses": {
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/round-glasses/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/round-glasses/happy/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "frameCount": 18,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "frameCount": 12,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      }
    }
  },
  "eyewear/silver-goggles": {
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/silver-goggles/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/eyewear/silver-goggles/happy/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "frameCount": 18,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "frameCount": 12,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      }
    }
  },
  "headwear/beige-beanie": {
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/beige-beanie/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/beige-beanie/happy/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "frameCount": 18,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "frameCount": 12,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      }
    }
  },
  "headwear/brown-beanie": {
    "sheets": {
      "ball-hit": {
        "frameCount": 18,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/brown-beanie/ball-hit/sheet.png"
      },
      "happy": {
        "frameCount": 12,
        "frameSize": {"w":64,"h":64},
        "characterOffsetY": 0,
        "grounded": true,
        "url": "/creatures/slimes/official/composition/headwear/brown-beanie/happy/sheet.png"
      }
    },
    "timelines": {
      "ball-hit": {
        "sheet": "ball-hit",
        "frameCount": 18,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0},
          {"sourceFrame":12,"dx":0,"dy":0},
          {"sourceFrame":13,"dx":0,"dy":0},
          {"sourceFrame":14,"dx":0,"dy":0},
          {"sourceFrame":15,"dx":0,"dy":0},
          {"sourceFrame":16,"dx":0,"dy":0},
          {"sourceFrame":17,"dx":0,"dy":0}
        ]
      },
      "happy": {
        "sheet": "happy",
        "frameCount": 12,
        "anchors": [
          {"sourceFrame":0,"dx":0,"dy":0},
          {"sourceFrame":1,"dx":0,"dy":0},
          {"sourceFrame":2,"dx":0,"dy":0},
          {"sourceFrame":3,"dx":0,"dy":0},
          {"sourceFrame":4,"dx":0,"dy":0},
          {"sourceFrame":5,"dx":0,"dy":0},
          {"sourceFrame":6,"dx":0,"dy":0},
          {"sourceFrame":7,"dx":0,"dy":0},
          {"sourceFrame":8,"dx":0,"dy":0},
          {"sourceFrame":9,"dx":0,"dy":0},
          {"sourceFrame":10,"dx":0,"dy":0},
          {"sourceFrame":11,"dx":0,"dy":0}
        ]
      }
    }
  },
} as const;
