import { StyleSheet } from "react-native";
import { borders, radii, spacing, tapMin, typography } from "../../theme/tokens";
import { songGuessStudentTheme as song } from "../../theme/song-guess";

export const songGuessBoardStyles = StyleSheet.create({
  scroll: { flex: 1, backgroundColor: song.bg },
  container: {
    flexGrow: 1,
    width: "100%",
    maxWidth: song.contentMaxWidth,
    alignSelf: "center",
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xxxl,
    gap: spacing.md,
    backgroundColor: song.bg,
  },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: song.bg,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    gap: spacing.md,
    padding: spacing.xl,
    backgroundColor: song.bg,
  },
  phaseRow: {
    minHeight: tapMin,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    paddingBottom: spacing.xs,
  },
  phaseLabel: { ...typography.title, color: song.text },
  roundText: { ...typography.badge, color: song.muted },
  roundTimerTrack: {
    height: song.progressHeight,
    overflow: "hidden",
    borderRadius: radii.pill,
    backgroundColor: song.track,
  },
  roundTimerFill: {
    height: spacing.xs,
    borderRadius: radii.pill,
    backgroundColor: song.accent,
  },
  questionText: {
    ...typography.subtitle,
    color: song.text,
    textAlign: "left",
  },
  joinTitle: { ...typography.subtitle, color: song.text },
  waitingCard: {
    gap: spacing.sm,
    padding: spacing.lg,
    borderRadius: song.answerRadius,
    borderCurve: "continuous",
    backgroundColor: song.surface,
    borderWidth: borders.hairline,
    borderColor: song.border,
  },
  playerCard: {
    gap: spacing.md,
    padding: spacing.lg,
    minHeight: song.playerCardMinHeight,
    borderRadius: song.answerRadius,
    borderCurve: "continuous",
    backgroundColor: song.surface,
    borderWidth: borders.hairline,
    borderColor: song.border,
  },
  playerMainRow: {
    minHeight: song.playerRowMinHeight,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.lg,
  },
  recordDisc: {
    width: song.recordSize,
    height: song.recordSize,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: song.recordRadius,
    borderWidth: song.recordBorderWidth,
    borderColor: song.disc,
    backgroundColor: song.track,
  },
  recordButton: {
    width: song.recordButtonSize,
    minWidth: song.recordButtonSize,
    minHeight: song.recordButtonSize,
    height: song.recordButtonSize,
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderWidth: borders.none,
    borderRadius: song.recordButtonRadius,
    backgroundColor: song.accent,
  },
  recordButtonText: { ...typography.badge, color: song.bg },
  playerInfo: { flex: 1, minWidth: 0, gap: spacing.xs },
  playerTopRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  playerDuration: { ...typography.micro, color: song.accent },
  playerTime: { ...typography.badge, color: song.muted },
  progressTrack: {
    height: song.progressHeight,
    overflow: "hidden",
    borderRadius: radii.pill,
    backgroundColor: song.track,
  },
  progressFill: {
    height: song.progressHeight,
    borderRadius: radii.pill,
    backgroundColor: song.accent,
  },
  playerActions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  playerButton: {
    flexGrow: 1,
    minWidth: tapMin * 2,
    borderColor: song.borderStrong,
    backgroundColor: song.accent,
  },
  playerButtonText: { color: song.bg },
  secondaryPlayerButton: {
    flexGrow: 1,
    minWidth: tapMin * 2,
    borderColor: song.borderStrong,
    backgroundColor: song.track,
  },
  secondaryPlayerButtonText: { color: song.text },
  playerError: { ...typography.badge, color: song.danger },
  /** Audio failure needs its own card (Figma `N4`): a one-line error under the
   * player did not tell students they can still answer from the clue. */
  audioErrorCard: {
    gap: spacing.sm,
    padding: spacing.lg,
    borderRadius: song.answerRadius,
    borderCurve: "continuous",
    backgroundColor: song.surface,
    borderWidth: borders.medium,
    borderColor: song.danger,
  },
  audioErrorTitle: { ...typography.subtitle, color: song.danger },
  audioErrorBody: { ...typography.body, color: song.muted },
  clueText: { ...typography.body, color: song.muted, textAlign: "center" },
  clueCard: {
    gap: spacing.xs,
    padding: spacing.lg,
    borderRadius: song.answerRadius,
    borderCurve: "continuous",
    backgroundColor: song.surface,
    borderWidth: borders.hairline,
    borderColor: song.border,
  },
  clueLabel: { ...typography.micro, color: song.accent },
  clueValue: { ...typography.label, color: song.text },

  answerCard: {
    gap: spacing.xs,
    padding: spacing.lg,
    borderRadius: song.answerRadius,
    backgroundColor: song.surface,
    borderWidth: borders.hairline,
    borderColor: song.border,
  },
  answerLabel: { ...typography.badge, color: song.muted },
  answerText: { ...typography.title, color: song.text },
  sessionFooter: { minHeight: tapMin, flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: spacing.md, paddingTop: spacing.md, borderTopWidth: borders.hairline, borderColor: song.border },
  sessionMeta: { ...typography.badge, color: song.muted },
  sessionScore: { ...typography.label, color: song.text },
  actions: { gap: spacing.sm },
  actionButton: { borderColor: song.borderStrong, backgroundColor: song.track },
  actionButtonText: { color: song.text },
  muted: { ...typography.body, color: song.muted },
  noticeText: { ...typography.body, color: song.success, textAlign: "center" },
  errorText: { ...typography.body, color: song.danger, textAlign: "center" },
});
