import { StyleSheet } from "react-native";
import { borders, radii, spacing, tapMin, typography } from "../../theme/tokens";
import { songGuessStudentTheme as song } from "../../theme/song-guess";

export const songGuessBoardStyles = StyleSheet.create({
  scroll: { flex: 1, backgroundColor: song.bg },
  container: {
    flexGrow: 1,
    width: "100%",
    maxWidth: song.contentMaxWidth,
    alignSelf: "center",
    padding: spacing.md,
    paddingBottom: spacing.xxxl,
    gap: spacing.md,
    backgroundColor: song.bg,
  },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: song.bg,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    gap: spacing.md,
    padding: spacing.xl,
    backgroundColor: song.bg,
  },
  phaseRow: {
    minHeight: tapMin,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    borderBottomWidth: borders.hairline,
    borderColor: song.border,
    paddingBottom: spacing.sm,
  },
  phaseLabel: { ...typography.subtitle, color: song.text },
  roundText: { ...typography.subtitle, color: song.muted },
  roundTimerTrack: {
    height: spacing.xs,
    overflow: "hidden",
    borderRadius: radii.pill,
    backgroundColor: song.track,
  },
  roundTimerFill: {
    height: spacing.xs,
    borderRadius: radii.pill,
    backgroundColor: song.accent,
  },
  questionText: {
    ...typography.title,
    color: song.text,
    textAlign: "center",
    paddingHorizontal: spacing.sm,
  },
  joinTitle: { ...typography.subtitle, color: song.text },
  waitingCard: {
    gap: spacing.sm,
    padding: spacing.lg,
    borderRadius: song.answerRadius,
    borderCurve: "continuous",
    backgroundColor: song.surface,
    borderWidth: borders.hairline,
    borderColor: song.border,
  },
  playerCard: {
    gap: spacing.lg,
    padding: spacing.lg,
    borderRadius: song.panelRadius,
    borderCurve: "continuous",
    backgroundColor: song.surface,
    borderWidth: borders.hairline,
    borderColor: song.border,
  },
  playerTopRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  playerDuration: { ...typography.display, color: song.text },
  playerTime: { ...typography.badge, color: song.muted },
  progressTrack: {
    height: spacing.sm,
    overflow: "hidden",
    borderRadius: radii.pill,
    backgroundColor: song.track,
  },
  progressFill: {
    height: spacing.sm,
    borderRadius: radii.pill,
    backgroundColor: song.accent,
  },
  playerActions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  playerButton: {
    flexGrow: 1,
    minWidth: tapMin * 2,
    borderColor: song.borderStrong,
    backgroundColor: song.accent,
  },
  playerButtonText: { color: song.bg },
  secondaryPlayerButton: {
    flexGrow: 1,
    minWidth: tapMin * 2,
    borderColor: song.borderStrong,
    backgroundColor: song.track,
  },
  secondaryPlayerButtonText: { color: song.text },
  playerError: { ...typography.badge, color: song.danger },
  clueText: { ...typography.body, color: song.muted, textAlign: "center" },
  resultText: { ...typography.subtitle, textAlign: "center" },
  successText: { color: song.success },
  missText: { color: song.danger },
  answerText: {
    ...typography.display,
    color: song.text,
    textAlign: "center",
    padding: spacing.lg,
    borderRadius: song.answerRadius,
    backgroundColor: song.surface,
  },
  actions: { gap: spacing.sm },
  actionButton: { borderColor: song.borderStrong, backgroundColor: song.track },
  actionButtonText: { color: song.text },
  muted: { ...typography.body, color: song.muted },
  noticeText: { ...typography.body, color: song.success, textAlign: "center" },
  errorText: { ...typography.body, color: song.danger, textAlign: "center" },
});
