// Generated by scripts/import-slime-assets.mjs. Do not edit by hand.

export const SLIME_WEB_ASSET_REGISTRY_018 = {
  "silver-crown-blue-gem/yellow/water-puddle": {
    "key": "silver-crown-blue-gem/yellow/water-puddle",
    "evolution": "silver-crown-blue-gem",
    "color": "yellow",
    "action": "water-puddle",
    "sheetUrl": "/creatures/slimes/official/silver-crown-blue-gem/yellow/water-puddle/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 0.aseprite",
          "frame": {"x":0,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 1.aseprite",
          "frame": {"x":64,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 2.aseprite",
          "frame": {"x":128,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 3.aseprite",
          "frame": {"x":192,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 4.aseprite",
          "frame": {"x":256,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 5.aseprite",
          "frame": {"x":320,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 6.aseprite",
          "frame": {"x":384,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 7.aseprite",
          "frame": {"x":448,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 8.aseprite",
          "frame": {"x":512,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 9.aseprite",
          "frame": {"x":576,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 10.aseprite",
          "frame": {"x":640,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 11.aseprite",
          "frame": {"x":704,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 12.aseprite",
          "frame": {"x":768,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 13.aseprite",
          "frame": {"x":832,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 14.aseprite",
          "frame": {"x":896,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 15.aseprite",
          "frame": {"x":960,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 16.aseprite",
          "frame": {"x":1024,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 17.aseprite",
          "frame": {"x":1088,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 18.aseprite",
          "frame": {"x":1152,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 19.aseprite",
          "frame": {"x":1216,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 20.aseprite",
          "frame": {"x":1280,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 21.aseprite",
          "frame": {"x":1344,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 22.aseprite",
          "frame": {"x":1408,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 23.aseprite",
          "frame": {"x":1472,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 24.aseprite",
          "frame": {"x":1536,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-water-puddle-silver-crown-blue-gem 25.aseprite",
          "frame": {"x":1600,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        }
      ],
      "meta": {
        "app": "https://www.aseprite.org/",
        "version": "1.x-dev",
        "image": "slime-yellow-water-puddle-silver-crown-blue-gem-sheet.png",
        "format": "RGBA8888",
        "size": {"w":1664,"h":75},
        "scale": "1"
      }
    }
  },
  "silver-crown-blue-gem/yellow/trampoline": {
    "key": "silver-crown-blue-gem/yellow/trampoline",
    "evolution": "silver-crown-blue-gem",
    "color": "yellow",
    "action": "trampoline",
    "sheetUrl": "/creatures/slimes/official/silver-crown-blue-gem/yellow/trampoline/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 0.aseprite",
          "frame": {"x":0,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 1.aseprite",
          "frame": {"x":64,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 2.aseprite",
          "frame": {"x":128,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 3.aseprite",
          "frame": {"x":192,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 4.aseprite",
          "frame": {"x":256,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 5.aseprite",
          "frame": {"x":320,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 6.aseprite",
          "frame": {"x":384,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 7.aseprite",
          "frame": {"x":448,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 8.aseprite",
          "frame": {"x":512,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 9.aseprite",
          "frame": {"x":576,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 10.aseprite",
          "frame": {"x":640,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 11.aseprite",
          "frame": {"x":704,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 12.aseprite",
          "frame": {"x":768,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 13.aseprite",
          "frame": {"x":832,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 14.aseprite",
          "frame": {"x":896,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 15.aseprite",
          "frame": {"x":960,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 16.aseprite",
          "frame": {"x":1024,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 17.aseprite",
          "frame": {"x":1088,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 18.aseprite",
          "frame": {"x":1152,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 19.aseprite",
          "frame": {"x":1216,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 20.aseprite",
          "frame": {"x":1280,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 21.aseprite",
          "frame": {"x":1344,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 22.aseprite",
          "frame": {"x":1408,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 23.aseprite",
          "frame": {"x":1472,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 24.aseprite",
          "frame": {"x":1536,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline-silver-crown-blue-gem 25.aseprite",
          "frame": {"x":1600,"y":0,"w":64,"h":75},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":75},
          "sourceSize": {"w":64,"h":75},
          "duration": 100
        }
      ],
      "meta": {
        "app": "https://www.aseprite.org/",
        "version": "1.x-dev",
        "image": "slime-yellow-trampoline-silver-crown-blue-gem-sheet.png",
        "format": "RGBA8888",
        "size": {"w":1664,"h":75},
        "scale": "1"
      }
    }
  },
  "silver-crown-blue-gem/purple/drink-lemonade": {
    "key": "silver-crown-blue-gem/purple/drink-lemonade",
    "evolution": "silver-crown-blue-gem",
    "color": "purple",
    "action": "drink-lemonade",
    "sheetUrl": "/creatures/slimes/official/silver-crown-blue-gem/purple/drink-lemonade/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "slime-purple-drink-lemonade-silver-crown-blue-gem 0.aseprite",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "slime-purple-drink-lemonade-silver-crown-blue-gem 1.aseprite",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "slime-purple-drink-lemonade-silver-crown-blue-gem 2.aseprite",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "slime-purple-drink-lemonade-silver-crown-blue-gem 3.aseprite",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "slime-purple-drink-lemonade-silver-crown-blue-gem 4.aseprite",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "slime-purple-drink-lemonade-silver-crown-blue-gem 5.aseprite",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "slime-purple-drink-lemonade-silver-crown-blue-gem 6.aseprite",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "slime-purple-drink-lemonade-silver-crown-blue-gem 7.aseprite",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "app": "https://www.aseprite.org/",
        "version": "1.x-dev",
        "image": "slime-purple-drink-lemonade-silver-crown-blue-gem-sheet.png",
        "format": "RGBA8888",
        "size": {"w":512,"h":64},
        "scale": "1",
        "frameTags": [{"name":"crowned_drink","from":0,"to":7,"direction":"forward","color":"#000000ff"}],
        "layers": [
          {"name":"slime","opacity":255,"blendMode":"normal"},
          {"name":"crown","opacity":255,"blendMode":"normal"},
          {"name":"lemonade_glass","opacity":255,"blendMode":"normal"}
        ]
      }
    }
  },
} as const;
