// Generated by scripts/import-slime-assets.mjs. Do not edit by hand.

export const SLIME_WEB_ASSET_REGISTRY_005 = {
  "base/yellow/happy": {
    "key": "base/yellow/happy",
    "evolution": "base",
    "color": "yellow",
    "action": "happy",
    "sheetUrl": "/creatures/slimes/official/base/yellow/happy/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "slime-yellow-happy-heart 0.aseprite",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "slime-yellow-happy-heart 1.aseprite",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "slime-yellow-happy-heart 2.aseprite",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 120
        },
        {
          "filename": "slime-yellow-happy-heart 3.aseprite",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 110
        },
        {
          "filename": "slime-yellow-happy-heart 4.aseprite",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 110
        },
        {
          "filename": "slime-yellow-happy-heart 5.aseprite",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 110
        },
        {
          "filename": "slime-yellow-happy-heart 6.aseprite",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 120
        },
        {
          "filename": "slime-yellow-happy-heart 7.aseprite",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 130
        },
        {
          "filename": "slime-yellow-happy-heart 8.aseprite",
          "frame": {"x":512,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 150
        },
        {
          "filename": "slime-yellow-happy-heart 9.aseprite",
          "frame": {"x":576,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 170
        },
        {
          "filename": "slime-yellow-happy-heart 10.aseprite",
          "frame": {"x":640,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 190
        },
        {
          "filename": "slime-yellow-happy-heart 11.aseprite",
          "frame": {"x":704,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 260
        }
      ],
      "meta": {
        "app": "https://www.aseprite.org/",
        "version": "1.x-dev",
        "image": "slime-yellow-happy-heart-sheet.png",
        "format": "RGBA8888",
        "size": {"w":768,"h":64},
        "scale": "1"
      }
    }
  },
  "base/yellow/drink-lemonade": {
    "key": "base/yellow/drink-lemonade",
    "evolution": "base",
    "color": "yellow",
    "action": "drink-lemonade",
    "sheetUrl": "/creatures/slimes/official/base/yellow/drink-lemonade/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-lemonade",
        "color": "yellow",
        "option": null,
        "source": "props/drink/lemonade/yellow/slime-yellow-drink-lemonade.aseprite",
        "source_sha256": "eccae73242f6451f1bc5ba93f0b3b96ee5adf1aaf16939a4de7eb1ef22794423",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/yellow/drink-strawberry-soda": {
    "key": "base/yellow/drink-strawberry-soda",
    "evolution": "base",
    "color": "yellow",
    "action": "drink-strawberry-soda",
    "sheetUrl": "/creatures/slimes/official/base/yellow/drink-strawberry-soda/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-strawberry-soda",
        "color": "yellow",
        "option": null,
        "source": "props/drink/strawberry-soda/yellow/slime-yellow-drink-strawberry-soda.aseprite",
        "source_sha256": "c54c0a0f56dc8643049a9ce2f3078eb35aca0d1b779ca35cb1ce89c5031699bb",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/yellow/drink-melon-soda": {
    "key": "base/yellow/drink-melon-soda",
    "evolution": "base",
    "color": "yellow",
    "action": "drink-melon-soda",
    "sheetUrl": "/creatures/slimes/official/base/yellow/drink-melon-soda/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-melon-soda",
        "color": "yellow",
        "option": null,
        "source": "props/drink/melon-soda/yellow/slime-yellow-drink-melon-soda.aseprite",
        "source_sha256": "3fcfe650977efdcbfb88a58ea1fb7c32864ae58982b18c2c260bc7085079e08b",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/yellow/drink-grape-soda": {
    "key": "base/yellow/drink-grape-soda",
    "evolution": "base",
    "color": "yellow",
    "action": "drink-grape-soda",
    "sheetUrl": "/creatures/slimes/official/base/yellow/drink-grape-soda/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-grape-soda",
        "color": "yellow",
        "option": null,
        "source": "props/drink/grape-soda/yellow/slime-yellow-drink-grape-soda.aseprite",
        "source_sha256": "df2cf53e0723bba6f8c0c7da74655a8702afb2cc295555013566d26138032a42",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/yellow/drink-blue-ramune": {
    "key": "base/yellow/drink-blue-ramune",
    "evolution": "base",
    "color": "yellow",
    "action": "drink-blue-ramune",
    "sheetUrl": "/creatures/slimes/official/base/yellow/drink-blue-ramune/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-blue-ramune",
        "color": "yellow",
        "option": null,
        "source": "props/drink/blue-ramune/yellow/slime-yellow-drink-blue-ramune.aseprite",
        "source_sha256": "8e5a140758b09bf97000ddad4349976329a70a664692a763de500b5870214382",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
} as const;
