// Generated by scripts/import-slime-assets.mjs. Do not edit by hand.

export const SLIME_WEB_ASSET_REGISTRY_002 = {
  "base/blue/drink-blue-ramune": {
    "key": "base/blue/drink-blue-ramune",
    "evolution": "base",
    "color": "blue",
    "action": "drink-blue-ramune",
    "sheetUrl": "/creatures/slimes/official/base/blue/drink-blue-ramune/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-blue-ramune",
        "color": "blue",
        "option": null,
        "source": "props/drink/blue-ramune/blue/slime-blue-drink-blue-ramune.aseprite",
        "source_sha256": "b77559cd78625d0e44fab5026d41d4f2e7443885fb19e49415b4217eefc55abb",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/blue/water-puddle": {
    "key": "base/blue/water-puddle",
    "evolution": "base",
    "color": "blue",
    "action": "water-puddle",
    "sheetUrl": "/creatures/slimes/official/base/blue/water-puddle/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "slime-blue 0.aseprite",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 1.aseprite",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 2.aseprite",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 3.aseprite",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 4.aseprite",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 5.aseprite",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 6.aseprite",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 7.aseprite",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 8.aseprite",
          "frame": {"x":512,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 9.aseprite",
          "frame": {"x":576,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 10.aseprite",
          "frame": {"x":640,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 11.aseprite",
          "frame": {"x":704,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 12.aseprite",
          "frame": {"x":768,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 13.aseprite",
          "frame": {"x":0,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 14.aseprite",
          "frame": {"x":64,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 15.aseprite",
          "frame": {"x":128,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 16.aseprite",
          "frame": {"x":192,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 17.aseprite",
          "frame": {"x":256,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 18.aseprite",
          "frame": {"x":320,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 19.aseprite",
          "frame": {"x":384,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 20.aseprite",
          "frame": {"x":448,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 21.aseprite",
          "frame": {"x":512,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 22.aseprite",
          "frame": {"x":576,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 23.aseprite",
          "frame": {"x":640,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 24.aseprite",
          "frame": {"x":704,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue 25.aseprite",
          "frame": {"x":768,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        }
      ],
      "meta": {
        "app": "https://www.aseprite.org/",
        "version": "1.x-dev",
        "image": "slime-blue-sheet.png",
        "format": "I8",
        "size": {"w":832,"h":128},
        "scale": "1",
        "frameTags": [{"name":"idle_jump","from":0,"to":25,"direction":"forward","color":"#000000ff"}]
      }
    }
  },
  "base/blue/trampoline": {
    "key": "base/blue/trampoline",
    "evolution": "base",
    "color": "blue",
    "action": "trampoline",
    "sheetUrl": "/creatures/slimes/official/base/blue/trampoline/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "slime-blue-trampoline 0.aseprite",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 1.aseprite",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 2.aseprite",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 3.aseprite",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 4.aseprite",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 5.aseprite",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 6.aseprite",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 7.aseprite",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 8.aseprite",
          "frame": {"x":512,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 9.aseprite",
          "frame": {"x":576,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 10.aseprite",
          "frame": {"x":640,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 11.aseprite",
          "frame": {"x":704,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 12.aseprite",
          "frame": {"x":768,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 13.aseprite",
          "frame": {"x":0,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 14.aseprite",
          "frame": {"x":64,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 15.aseprite",
          "frame": {"x":128,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 16.aseprite",
          "frame": {"x":192,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 17.aseprite",
          "frame": {"x":256,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 18.aseprite",
          "frame": {"x":320,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 19.aseprite",
          "frame": {"x":384,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 20.aseprite",
          "frame": {"x":448,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 21.aseprite",
          "frame": {"x":512,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 22.aseprite",
          "frame": {"x":576,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 23.aseprite",
          "frame": {"x":640,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 24.aseprite",
          "frame": {"x":704,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-blue-trampoline 25.aseprite",
          "frame": {"x":768,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        }
      ],
      "meta": {
        "app": "https://www.aseprite.org/",
        "version": "1.x-dev",
        "image": "slime-blue-trampoline-sheet.png",
        "format": "RGBA8888",
        "size": {"w":832,"h":128},
        "scale": "1",
        "frameTags": [{"name":"trampoline_jump","from":0,"to":25,"direction":"forward","color":"#000000ff"}],
        "layers": [
          {"name":"trampoline","opacity":255,"blendMode":"normal"},
          {"name":"slime","opacity":255,"blendMode":"normal"}
        ]
      }
    }
  },
  "base/green/idle": {
    "key": "base/green/idle",
    "evolution": "base",
    "color": "green",
    "action": "idle",
    "sheetUrl": "/creatures/slimes/official/base/green/idle/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "slime-green-idle 0.aseprite",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 240
        },
        {
          "filename": "slime-green-idle 1.aseprite",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "slime-green-idle 2.aseprite",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "slime-green-idle 3.aseprite",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 90
        },
        {
          "filename": "slime-green-idle 4.aseprite",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 90
        },
        {
          "filename": "slime-green-idle 5.aseprite",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "slime-green-idle 6.aseprite",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "slime-green-idle 7.aseprite",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 240
        }
      ],
      "meta": {
        "app": "https://www.aseprite.org/",
        "version": "1.x-dev",
        "image": "slime-green-idle-sheet.png",
        "format": "RGBA8888",
        "size": {"w":512,"h":64},
        "scale": "1",
        "frameTags": [{"name":"idle","from":0,"to":7,"direction":"forward","color":"#000000ff"}],
        "layers": [{"name":"slime","opacity":255,"blendMode":"normal"}]
      }
    }
  },
} as const;
