// Generated by scripts/import-slime-assets.mjs. Do not edit by hand.

export const SLIME_WEB_ASSET_REGISTRY_001 = {
  "base/blue/idle": {
    "key": "base/blue/idle",
    "evolution": "base",
    "color": "blue",
    "action": "idle",
    "sheetUrl": "/creatures/slimes/official/base/blue/idle/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "slime-blue-idle 0.aseprite",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 240
        },
        {
          "filename": "slime-blue-idle 1.aseprite",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "slime-blue-idle 2.aseprite",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "slime-blue-idle 3.aseprite",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 90
        },
        {
          "filename": "slime-blue-idle 4.aseprite",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 90
        },
        {
          "filename": "slime-blue-idle 5.aseprite",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "slime-blue-idle 6.aseprite",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "slime-blue-idle 7.aseprite",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 240
        }
      ],
      "meta": {
        "app": "https://www.aseprite.org/",
        "version": "1.x-dev",
        "image": "slime-blue-idle-sheet.png",
        "format": "RGBA8888",
        "size": {"w":512,"h":64},
        "scale": "1",
        "frameTags": [{"name":"idle","from":0,"to":7,"direction":"forward","color":"#000000ff"}],
        "layers": [{"name":"slime","opacity":255,"blendMode":"normal"}]
      }
    }
  },
  "base/blue/happy": {
    "key": "base/blue/happy",
    "evolution": "base",
    "color": "blue",
    "action": "happy",
    "sheetUrl": "/creatures/slimes/official/base/blue/happy/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "slime-blue-happy-heart 0.aseprite",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "slime-blue-happy-heart 1.aseprite",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "slime-blue-happy-heart 2.aseprite",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 120
        },
        {
          "filename": "slime-blue-happy-heart 3.aseprite",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 110
        },
        {
          "filename": "slime-blue-happy-heart 4.aseprite",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 110
        },
        {
          "filename": "slime-blue-happy-heart 5.aseprite",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 110
        },
        {
          "filename": "slime-blue-happy-heart 6.aseprite",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 120
        },
        {
          "filename": "slime-blue-happy-heart 7.aseprite",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 130
        },
        {
          "filename": "slime-blue-happy-heart 8.aseprite",
          "frame": {"x":512,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 150
        },
        {
          "filename": "slime-blue-happy-heart 9.aseprite",
          "frame": {"x":576,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 170
        },
        {
          "filename": "slime-blue-happy-heart 10.aseprite",
          "frame": {"x":640,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 190
        },
        {
          "filename": "slime-blue-happy-heart 11.aseprite",
          "frame": {"x":704,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 260
        }
      ],
      "meta": {
        "app": "https://www.aseprite.org/",
        "version": "1.x-dev",
        "image": "slime-blue-happy-heart-sheet.png",
        "format": "RGBA8888",
        "size": {"w":768,"h":64},
        "scale": "1"
      }
    }
  },
  "base/blue/drink-lemonade": {
    "key": "base/blue/drink-lemonade",
    "evolution": "base",
    "color": "blue",
    "action": "drink-lemonade",
    "sheetUrl": "/creatures/slimes/official/base/blue/drink-lemonade/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-lemonade",
        "color": "blue",
        "option": null,
        "source": "props/drink/lemonade/blue/slime-blue-drink-lemonade.aseprite",
        "source_sha256": "cb3cba85404140d18672508b5afefc8770ad1101f6a3e6ffd63912afceedbb0d",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/blue/drink-strawberry-soda": {
    "key": "base/blue/drink-strawberry-soda",
    "evolution": "base",
    "color": "blue",
    "action": "drink-strawberry-soda",
    "sheetUrl": "/creatures/slimes/official/base/blue/drink-strawberry-soda/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-strawberry-soda",
        "color": "blue",
        "option": null,
        "source": "props/drink/strawberry-soda/blue/slime-blue-drink-strawberry-soda.aseprite",
        "source_sha256": "1bd3c569d1a9064a75d490d9015729999710d22bdf4818d03db1b20f3f66852a",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/blue/drink-melon-soda": {
    "key": "base/blue/drink-melon-soda",
    "evolution": "base",
    "color": "blue",
    "action": "drink-melon-soda",
    "sheetUrl": "/creatures/slimes/official/base/blue/drink-melon-soda/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-melon-soda",
        "color": "blue",
        "option": null,
        "source": "props/drink/melon-soda/blue/slime-blue-drink-melon-soda.aseprite",
        "source_sha256": "ccbfbd37a03b1c0801c71cd93c678686753b993e2abc462c4096f0ccc0cd7d7a",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/blue/drink-grape-soda": {
    "key": "base/blue/drink-grape-soda",
    "evolution": "base",
    "color": "blue",
    "action": "drink-grape-soda",
    "sheetUrl": "/creatures/slimes/official/base/blue/drink-grape-soda/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-grape-soda",
        "color": "blue",
        "option": null,
        "source": "props/drink/grape-soda/blue/slime-blue-drink-grape-soda.aseprite",
        "source_sha256": "17d7a2ffd9b867d14686360caf66bacc7968b54921bfedd0d3588faf4d261da0",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
} as const;
