// Generated by scripts/import-slime-assets.mjs. Do not edit by hand.

export const SLIME_WEB_ASSET_REGISTRY_007 = {
  "base/purple/happy": {
    "key": "base/purple/happy",
    "evolution": "base",
    "color": "purple",
    "action": "happy",
    "sheetUrl": "/creatures/slimes/official/base/purple/happy/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "slime-purple-happy-heart 0.aseprite",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "slime-purple-happy-heart 1.aseprite",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "slime-purple-happy-heart 2.aseprite",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 120
        },
        {
          "filename": "slime-purple-happy-heart 3.aseprite",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 110
        },
        {
          "filename": "slime-purple-happy-heart 4.aseprite",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 110
        },
        {
          "filename": "slime-purple-happy-heart 5.aseprite",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 110
        },
        {
          "filename": "slime-purple-happy-heart 6.aseprite",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 120
        },
        {
          "filename": "slime-purple-happy-heart 7.aseprite",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 130
        },
        {
          "filename": "slime-purple-happy-heart 8.aseprite",
          "frame": {"x":512,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 150
        },
        {
          "filename": "slime-purple-happy-heart 9.aseprite",
          "frame": {"x":576,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 170
        },
        {
          "filename": "slime-purple-happy-heart 10.aseprite",
          "frame": {"x":640,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 190
        },
        {
          "filename": "slime-purple-happy-heart 11.aseprite",
          "frame": {"x":704,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 260
        }
      ],
      "meta": {
        "app": "https://www.aseprite.org/",
        "version": "1.x-dev",
        "image": "slime-purple-happy-heart-sheet.png",
        "format": "RGBA8888",
        "size": {"w":768,"h":64},
        "scale": "1"
      }
    }
  },
  "base/purple/drink-lemonade": {
    "key": "base/purple/drink-lemonade",
    "evolution": "base",
    "color": "purple",
    "action": "drink-lemonade",
    "sheetUrl": "/creatures/slimes/official/base/purple/drink-lemonade/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-lemonade",
        "color": "purple",
        "option": null,
        "source": "props/drink/lemonade/purple/slime-purple-drink-lemonade.aseprite",
        "source_sha256": "182fcec6dadb41bbc4ceaaae147ebe59c02d4cc8c25cc817a8a13c978ea24ca8",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/purple/drink-strawberry-soda": {
    "key": "base/purple/drink-strawberry-soda",
    "evolution": "base",
    "color": "purple",
    "action": "drink-strawberry-soda",
    "sheetUrl": "/creatures/slimes/official/base/purple/drink-strawberry-soda/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-strawberry-soda",
        "color": "purple",
        "option": null,
        "source": "props/drink/strawberry-soda/purple/slime-purple-drink-strawberry-soda.aseprite",
        "source_sha256": "661acf4eab09a1f19a4eee7e7a42cb4213163533b9d3b112f05732f85e19137a",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/purple/drink-melon-soda": {
    "key": "base/purple/drink-melon-soda",
    "evolution": "base",
    "color": "purple",
    "action": "drink-melon-soda",
    "sheetUrl": "/creatures/slimes/official/base/purple/drink-melon-soda/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-melon-soda",
        "color": "purple",
        "option": null,
        "source": "props/drink/melon-soda/purple/slime-purple-drink-melon-soda.aseprite",
        "source_sha256": "fca001e0fbe554a6a969f1efe372bff69db78321ae71d762431b500948309dbe",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/purple/drink-grape-soda": {
    "key": "base/purple/drink-grape-soda",
    "evolution": "base",
    "color": "purple",
    "action": "drink-grape-soda",
    "sheetUrl": "/creatures/slimes/official/base/purple/drink-grape-soda/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-grape-soda",
        "color": "purple",
        "option": null,
        "source": "props/drink/grape-soda/purple/slime-purple-drink-grape-soda.aseprite",
        "source_sha256": "23bce34a8bfc9b02dd23be7fbafb4246702eacfa3b58d5e04f483403d0fb5526",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/purple/drink-blue-ramune": {
    "key": "base/purple/drink-blue-ramune",
    "evolution": "base",
    "color": "purple",
    "action": "drink-blue-ramune",
    "sheetUrl": "/creatures/slimes/official/base/purple/drink-blue-ramune/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-blue-ramune",
        "color": "purple",
        "option": null,
        "source": "props/drink/blue-ramune/purple/slime-purple-drink-blue-ramune.aseprite",
        "source_sha256": "bb052f14aae28c8d3864546b4d2bc6a55f67eb26a519431a20f05baba28f0c91",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
} as const;
