// Generated by scripts/import-slime-assets.mjs. Do not edit by hand.

export const SLIME_WEB_ASSET_REGISTRY_003 = {
  "base/green/happy": {
    "key": "base/green/happy",
    "evolution": "base",
    "color": "green",
    "action": "happy",
    "sheetUrl": "/creatures/slimes/official/base/green/happy/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "slime-green-happy-heart 0.aseprite",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "slime-green-happy-heart 1.aseprite",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "slime-green-happy-heart 2.aseprite",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 120
        },
        {
          "filename": "slime-green-happy-heart 3.aseprite",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 110
        },
        {
          "filename": "slime-green-happy-heart 4.aseprite",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 110
        },
        {
          "filename": "slime-green-happy-heart 5.aseprite",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 110
        },
        {
          "filename": "slime-green-happy-heart 6.aseprite",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 120
        },
        {
          "filename": "slime-green-happy-heart 7.aseprite",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 130
        },
        {
          "filename": "slime-green-happy-heart 8.aseprite",
          "frame": {"x":512,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 150
        },
        {
          "filename": "slime-green-happy-heart 9.aseprite",
          "frame": {"x":576,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 170
        },
        {
          "filename": "slime-green-happy-heart 10.aseprite",
          "frame": {"x":640,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 190
        },
        {
          "filename": "slime-green-happy-heart 11.aseprite",
          "frame": {"x":704,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 260
        }
      ],
      "meta": {
        "app": "https://www.aseprite.org/",
        "version": "1.x-dev",
        "image": "slime-green-happy-heart-sheet.png",
        "format": "RGBA8888",
        "size": {"w":768,"h":64},
        "scale": "1"
      }
    }
  },
  "base/green/drink-lemonade": {
    "key": "base/green/drink-lemonade",
    "evolution": "base",
    "color": "green",
    "action": "drink-lemonade",
    "sheetUrl": "/creatures/slimes/official/base/green/drink-lemonade/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-lemonade",
        "color": "green",
        "option": null,
        "source": "props/drink/lemonade/green/slime-green-drink-lemonade.aseprite",
        "source_sha256": "cdd2a97b76f915985a4ab42407c383936676ea40a91dae6ac3b0cc59998dab41",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/green/drink-strawberry-soda": {
    "key": "base/green/drink-strawberry-soda",
    "evolution": "base",
    "color": "green",
    "action": "drink-strawberry-soda",
    "sheetUrl": "/creatures/slimes/official/base/green/drink-strawberry-soda/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-strawberry-soda",
        "color": "green",
        "option": null,
        "source": "props/drink/strawberry-soda/green/slime-green-drink-strawberry-soda.aseprite",
        "source_sha256": "cfea2f28893e1a65663f42c36f20e1d46c1cb393ea4bfa59134cce185f094e52",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/green/drink-melon-soda": {
    "key": "base/green/drink-melon-soda",
    "evolution": "base",
    "color": "green",
    "action": "drink-melon-soda",
    "sheetUrl": "/creatures/slimes/official/base/green/drink-melon-soda/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-melon-soda",
        "color": "green",
        "option": null,
        "source": "props/drink/melon-soda/green/slime-green-drink-melon-soda.aseprite",
        "source_sha256": "909518623cee1ab47b22077696ce577893e0a65873f650a2d4750628ef77d198",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/green/drink-grape-soda": {
    "key": "base/green/drink-grape-soda",
    "evolution": "base",
    "color": "green",
    "action": "drink-grape-soda",
    "sheetUrl": "/creatures/slimes/official/base/green/drink-grape-soda/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-grape-soda",
        "color": "green",
        "option": null,
        "source": "props/drink/grape-soda/green/slime-green-drink-grape-soda.aseprite",
        "source_sha256": "f9b506a6ad6fcf90836f5d20f27f0fd7256febc220e44234f56cfd55a9b96d87",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
  "base/green/drink-blue-ramune": {
    "key": "base/green/drink-blue-ramune",
    "evolution": "base",
    "color": "green",
    "action": "drink-blue-ramune",
    "sheetUrl": "/creatures/slimes/official/base/green/drink-blue-ramune/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "0",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 220
        },
        {
          "filename": "1",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "2",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "3",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "4",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 140
        },
        {
          "filename": "5",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "6",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "7",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 280
        }
      ],
      "meta": {
        "image": "slime.png",
        "size": {"w":512,"h":64},
        "frame_size": {"w":64,"h":64},
        "frame_count": 8,
        "alpha": "binary",
        "role": "slime",
        "action": "drink-blue-ramune",
        "color": "green",
        "option": null,
        "source": "props/drink/blue-ramune/green/slime-green-drink-blue-ramune.aseprite",
        "source_sha256": "364e730f8d7bdaf8a02e1fde13f9a762c884c4ae647499812f3830d8ad59fb37",
        "transforms": [
          {"source_idle_frame":0,"dx":0,"dy":0},
          {"source_idle_frame":1,"dx":0,"dy":0},
          {"source_idle_frame":2,"dx":0,"dy":0},
          {"source_idle_frame":3,"dx":0,"dy":0},
          {"source_idle_frame":4,"dx":0,"dy":0},
          {"source_idle_frame":5,"dx":0,"dy":0},
          {"source_idle_frame":6,"dx":0,"dy":0},
          {"source_idle_frame":7,"dx":0,"dy":0}
        ]
      }
    }
  },
} as const;
