// Generated by scripts/import-slime-assets.mjs. Do not edit by hand.

export const SLIME_WEB_ASSET_REGISTRY_006 = {
  "base/yellow/water-puddle": {
    "key": "base/yellow/water-puddle",
    "evolution": "base",
    "color": "yellow",
    "action": "water-puddle",
    "sheetUrl": "/creatures/slimes/official/base/yellow/water-puddle/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "slime-yellow 0.aseprite",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 1.aseprite",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 2.aseprite",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 3.aseprite",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 4.aseprite",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 5.aseprite",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 6.aseprite",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 7.aseprite",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 8.aseprite",
          "frame": {"x":512,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 9.aseprite",
          "frame": {"x":576,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 10.aseprite",
          "frame": {"x":640,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 11.aseprite",
          "frame": {"x":704,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 12.aseprite",
          "frame": {"x":768,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 13.aseprite",
          "frame": {"x":0,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 14.aseprite",
          "frame": {"x":64,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 15.aseprite",
          "frame": {"x":128,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 16.aseprite",
          "frame": {"x":192,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 17.aseprite",
          "frame": {"x":256,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 18.aseprite",
          "frame": {"x":320,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 19.aseprite",
          "frame": {"x":384,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 20.aseprite",
          "frame": {"x":448,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 21.aseprite",
          "frame": {"x":512,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 22.aseprite",
          "frame": {"x":576,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 23.aseprite",
          "frame": {"x":640,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 24.aseprite",
          "frame": {"x":704,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow 25.aseprite",
          "frame": {"x":768,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        }
      ],
      "meta": {
        "app": "https://www.aseprite.org/",
        "version": "1.x-dev",
        "image": "slime-yellow-sheet.png",
        "format": "I8",
        "size": {"w":832,"h":128},
        "scale": "1",
        "frameTags": [{"name":"idle_jump","from":0,"to":25,"direction":"forward","color":"#000000ff"}]
      }
    }
  },
  "base/yellow/trampoline": {
    "key": "base/yellow/trampoline",
    "evolution": "base",
    "color": "yellow",
    "action": "trampoline",
    "sheetUrl": "/creatures/slimes/official/base/yellow/trampoline/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "slime-yellow-trampoline 0.aseprite",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 1.aseprite",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 2.aseprite",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 3.aseprite",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 4.aseprite",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 5.aseprite",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 6.aseprite",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 7.aseprite",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 8.aseprite",
          "frame": {"x":512,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 9.aseprite",
          "frame": {"x":576,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 10.aseprite",
          "frame": {"x":640,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 11.aseprite",
          "frame": {"x":704,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 12.aseprite",
          "frame": {"x":768,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 13.aseprite",
          "frame": {"x":0,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 14.aseprite",
          "frame": {"x":64,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 15.aseprite",
          "frame": {"x":128,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 16.aseprite",
          "frame": {"x":192,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 17.aseprite",
          "frame": {"x":256,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 18.aseprite",
          "frame": {"x":320,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 19.aseprite",
          "frame": {"x":384,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 20.aseprite",
          "frame": {"x":448,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 21.aseprite",
          "frame": {"x":512,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 22.aseprite",
          "frame": {"x":576,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 23.aseprite",
          "frame": {"x":640,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 24.aseprite",
          "frame": {"x":704,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        },
        {
          "filename": "slime-yellow-trampoline 25.aseprite",
          "frame": {"x":768,"y":64,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 100
        }
      ],
      "meta": {
        "app": "https://www.aseprite.org/",
        "version": "1.x-dev",
        "image": "slime-yellow-trampoline-sheet.png",
        "format": "RGBA8888",
        "size": {"w":832,"h":128},
        "scale": "1",
        "frameTags": [{"name":"trampoline_jump","from":0,"to":25,"direction":"forward","color":"#000000ff"}],
        "layers": [
          {"name":"trampoline","opacity":255,"blendMode":"normal"},
          {"name":"slime","opacity":255,"blendMode":"normal"}
        ]
      }
    }
  },
  "base/purple/idle": {
    "key": "base/purple/idle",
    "evolution": "base",
    "color": "purple",
    "action": "idle",
    "sheetUrl": "/creatures/slimes/official/base/purple/idle/sheet.png",
    "metadata": {
      "frames": [
        {
          "filename": "slime-purple-idle 0.aseprite",
          "frame": {"x":0,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 240
        },
        {
          "filename": "slime-purple-idle 1.aseprite",
          "frame": {"x":64,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "slime-purple-idle 2.aseprite",
          "frame": {"x":128,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "slime-purple-idle 3.aseprite",
          "frame": {"x":192,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 90
        },
        {
          "filename": "slime-purple-idle 4.aseprite",
          "frame": {"x":256,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 90
        },
        {
          "filename": "slime-purple-idle 5.aseprite",
          "frame": {"x":320,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 160
        },
        {
          "filename": "slime-purple-idle 6.aseprite",
          "frame": {"x":384,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 180
        },
        {
          "filename": "slime-purple-idle 7.aseprite",
          "frame": {"x":448,"y":0,"w":64,"h":64},
          "rotated": false,
          "trimmed": false,
          "spriteSourceSize": {"x":0,"y":0,"w":64,"h":64},
          "sourceSize": {"w":64,"h":64},
          "duration": 240
        }
      ],
      "meta": {
        "app": "https://www.aseprite.org/",
        "version": "1.x-dev",
        "image": "slime-purple-idle-sheet.png",
        "format": "RGBA8888",
        "size": {"w":512,"h":64},
        "scale": "1",
        "frameTags": [{"name":"idle","from":0,"to":7,"direction":"forward","color":"#000000ff"}],
        "layers": [{"name":"slime","opacity":255,"blendMode":"normal"}]
      }
    }
  },
} as const;
