// Generated by scripts/import-slime-assets.mjs. Do not edit by hand.

export const SLIME_WEB_CROWN_OVERLAY_REGISTRY_001 = {
  "gold-crown-red-gem/blue": {
    "key": "gold-crown-red-gem/blue",
    "imageUrl": "/creatures/slimes/official/overlays/gold-crown-red-gem/blue/overlay.png",
    "imageScale": 1,
    "differingPixels": 298
  },
  "gold-crown-red-gem/green": {
    "key": "gold-crown-red-gem/green",
    "imageUrl": "/creatures/slimes/official/overlays/gold-crown-red-gem/green/overlay.png",
    "imageScale": 1,
    "differingPixels": 424
  },
  "gold-crown-red-gem/purple": {
    "key": "gold-crown-red-gem/purple",
    "imageUrl": "/creatures/slimes/official/overlays/gold-crown-red-gem/purple/overlay.png",
    "imageScale": 1,
    "differingPixels": 298
  },
  "gold-crown-red-gem/red": {
    "key": "gold-crown-red-gem/red",
    "imageUrl": "/creatures/slimes/official/overlays/gold-crown-red-gem/red/overlay.png",
    "imageScale": 1,
    "differingPixels": 298
  },
  "gold-crown-red-gem/yellow": {
    "key": "gold-crown-red-gem/yellow",
    "imageUrl": "/creatures/slimes/official/overlays/gold-crown-red-gem/yellow/overlay.png",
    "imageScale": 1,
    "differingPixels": 298
  },
  "silver-crown-blue-gem/blue": {
    "key": "silver-crown-blue-gem/blue",
    "imageUrl": "/creatures/slimes/official/overlays/silver-crown-blue-gem/blue/overlay.png",
    "imageScale": 1,
    "differingPixels": 312
  },
  "silver-crown-blue-gem/green": {
    "key": "silver-crown-blue-gem/green",
    "imageUrl": "/creatures/slimes/official/overlays/silver-crown-blue-gem/green/overlay.png",
    "imageScale": 1,
    "differingPixels": 435
  },
  "silver-crown-blue-gem/purple": {
    "key": "silver-crown-blue-gem/purple",
    "imageUrl": "/creatures/slimes/official/overlays/silver-crown-blue-gem/purple/overlay.png",
    "imageScale": 1,
    "differingPixels": 531
  },
  "silver-crown-blue-gem/red": {
    "key": "silver-crown-blue-gem/red",
    "imageUrl": "/creatures/slimes/official/overlays/silver-crown-blue-gem/red/overlay.png",
    "imageScale": 1,
    "differingPixels": 312
  },
  "silver-crown-blue-gem/yellow": {
    "key": "silver-crown-blue-gem/yellow",
    "imageUrl": "/creatures/slimes/official/overlays/silver-crown-blue-gem/yellow/overlay.png",
    "imageScale": 1,
    "differingPixels": 312
  },
} as const;
