import { useEffect, useMemo, useRef, useState } from "react";
import { Image, type ImageProps } from "expo-image";
import MaskedView from "@react-native-masked-view/masked-view";
import { StyleSheet, View } from "react-native";
import { layers } from "../../theme/tokens";
import { getApiBase } from "../../lib/api";
import {
  getSlimeFrame,
  resolveSlimeAsset,
  SLIME_SHARED_ASSETS,
  type SlimeAction,
  type SlimeColor,
  type SlimeEvolution,
  type EquippedFloor,
  type SlimeFrame,
} from "../../lib/slime-assets";
import { resolveSlimeRemoteSpriteUri } from "../../lib/slimes";
import { resolveSlimeWearables } from "../../lib/slime-wearables";
import {
  type SlimeSpriteProps,
} from "./slime-types";

const DEFAULT_DISPLAY_SCALE = 1;
const TRAMPOLINE_FLOOR_SOURCE = require("../../assets/slimes/shared/trampoline-floor.png");
/**
 * Single alpha mask reproducing the previous four-edge feather product.
 * Generated by `scripts/generate-feather-mask.mjs`.
 */
const SCENE_BACKGROUND_FEATHER_MASK = require("../../assets/slimes/shared/scene-background-feather-mask.png");
type LocalImageSource = ImageProps["source"];

function normalizedDisplayScale(value: number | undefined): number {
  if (!Number.isFinite(value)) return DEFAULT_DISPLAY_SCALE;
  return Math.max(0.25, Math.round((value as number) * 4) / 4);
}

function imageSource(value: unknown): LocalImageSource {
  // The generated registry contains only literal Metro `require` values.
  // Keeping this cast at the render boundary prevents a remote URI from ever
  // entering the sprite player.
  return value as LocalImageSource;
}

function sourceSize(frame: SlimeFrame, imageScale: number, scale: number) {
  return {
    width: frame.sourceSize.w * imageScale * scale,
    height: frame.sourceSize.h * imageScale * scale,
  };
}

function frameOffset(
  frame: SlimeFrame,
  imageScale: number,
  scale: number,
  offsetY: number,
) {
  return {
    left: (frame.spriteSourceSize.x - frame.frame.x) * imageScale * scale,
    top:
      (frame.spriteSourceSize.y - frame.frame.y) * imageScale * scale +
      offsetY,
  };
}

/**
 * Scene background with feathered edges.
 *
 * This used to nest one `MaskedView` per edge, each with its own SVG gradient.
 * Nested masks multiply alpha, so an animated background paid four native masking
 * stages every frame, and a class list or the shop grid multiplied that by the
 * number of mounted backgrounds.
 *
 * The generated mask asset already contains that same alpha product
 * (`H(x) * V(y)`), so one masking stage now produces the identical result. The
 * feather is a fixed 1/16 of each axis, so stretching one mask to any square
 * container stays proportional and no per-size mask is needed.
 *
 * Regenerate the asset with `node scripts/generate-feather-mask.mjs`.
 */
function FeatheredBackground({
  backgroundUri,
  sizeStyle,
}: {
  backgroundUri: string;
  sizeStyle: { width: number; height: number };
}) {
  return (
    <View
      pointerEvents="none"
      style={[styles.layer, styles.backgroundLayer, sizeStyle]}
      accessible={false}
    >
      <MaskedView
        style={StyleSheet.absoluteFill}
        maskElement={
          <Image
            source={SCENE_BACKGROUND_FEATHER_MASK}
            style={StyleSheet.absoluteFill}
            // The mask is authored at 128px and carries a proportional feather, so
            // it must stretch to the container rather than preserve its ratio.
            contentFit="fill"
            transition={0}
            accessible={false}
          />
        }
      >
        <Image
          source={{ uri: backgroundUri }}
          style={StyleSheet.absoluteFill}
          contentFit="cover"
          recyclingKey={`background:${backgroundUri}`}
          transition={0}
          accessible={false}
        />
      </MaskedView>
    </View>
  );
}

/**
 * Native player for the imported official slime sheets.
 *
 * The PNGs are generated nearest-scaled at 4x. We therefore render their
 * physical dimensions exactly and crop the packed sheet inside a viewport;
 * no dynamic require, URL, interpolation, or CSS animation is involved.
 */
export function SlimeSprite({
  slimeColor,
  evolution = "base",
  action = "idle",
  equippedFloor = "none",
  displayScale: requestedDisplayScale = DEFAULT_DISPLAY_SCALE,
  accessibilityLabel,
  repeat = false,
  itemSpritePath,
  backgroundSpritePath,
  wearables,
  drinkFlavor,
  growthStage,
  onComplete,
}: SlimeSpriteProps) {
  const displayScale = normalizedDisplayScale(requestedDisplayScale);
  const resolution = useMemo(
    () => resolveSlimeAsset({
      slimeColor,
      evolution,
      action,
      equippedFloor,
      growthStage,
      equippedHeadwear: wearables?.headwear ?? null,
      drinkFlavor,
    }),
    [action, drinkFlavor, equippedFloor, evolution, growthStage, slimeColor, wearables?.headwear],
  );
  const playbackKey = `${resolution.key}:${resolution.action}:${resolution.equippedFloor}`;
  const [frameIndex, setFrameIndex] = useState(0);
  const completedPlaybackRef = useRef<string | null>(null);
  const onCompleteRef = useRef(onComplete);
  onCompleteRef.current = onComplete;

  const frame = getSlimeFrame(resolution, frameIndex);
  const staticFloor = resolution.staticFloor;
  // Wearables compose onto the character sheet. Legacy complete-GIF props
  // replace that sheet entirely, so the two paths stay mutually exclusive.
  // The head slot is owned by the resolver: it decides whether this action draws
  // the growth crown, a player hat, or nothing. Other roles come from the
  // caller's selection. Legacy complete-GIF props replace the character sheet
  // entirely, so they suppress all composition.
  const resolvedWearables = useMemo(
    () => {
      if (itemSpritePath || resolution.composition.mode !== "composed") return [];
      const selection = { ...wearables, headwear: resolution.renderedHeadwear };
      return resolveSlimeWearables(
        selection,
        slimeColor,
        resolution.resolvedAction,
        frameIndex,
        resolution.drinkFlavor,
      );
    },
    [
      frameIndex,
      itemSpritePath,
      resolution.composition.mode,
      resolution.drinkFlavor,
      resolution.renderedHeadwear,
      resolution.resolvedAction,
      slimeColor,
      wearables,
    ],
  );
  const floorRise = staticFloor
    ? (staticFloor.slimeFootY - staticFloor.surfaceY) * resolution.imageScale * displayScale
    : 0;
  const viewport = {
    ...sourceSize(frame, resolution.imageScale, displayScale),
    height: frame.sourceSize.h * resolution.imageScale * displayScale + floorRise,
  };
  const packedSheetSize = {
    width: resolution.metadata.meta.size.w * resolution.imageScale * displayScale,
    height: resolution.metadata.meta.size.h * resolution.imageScale * displayScale,
  };
  const offset = frameOffset(frame, resolution.imageScale, displayScale, 0);
  const squareSourceSize = frame.sourceSize.w * resolution.imageScale * displayScale;

  useEffect(() => {
    setFrameIndex(0);
    completedPlaybackRef.current = null;
  }, [playbackKey]);

  useEffect(() => {
    const currentFrame = getSlimeFrame(resolution, frameIndex);
    const timeoutId = setTimeout(() => {
      const isLastFrame = frameIndex >= resolution.frameCount - 1;
      if (resolution.oneShot && isLastFrame && !repeat) {
        if (completedPlaybackRef.current !== playbackKey) {
          completedPlaybackRef.current = playbackKey;
          onCompleteRef.current?.();
        }
        return;
      }

      setFrameIndex((current) =>
        resolution.loop || repeat
          ? (current + 1) % resolution.frameCount
          : Math.min(current + 1, resolution.frameCount - 1),
      );
    }, Math.max(0, currentFrame.duration));

    return () => clearTimeout(timeoutId);
  }, [frameIndex, playbackKey, repeat, resolution]);

  const puddleAsset = equippedFloor === "water-puddle"
    ? SLIME_SHARED_ASSETS.sharedPuddle
    : null;
  const puddleFrame = puddleAsset
    ? getSlimeFrame({ metadata: puddleAsset.metadata }, frameIndex)
    : null;
  const puddlePackedSheetSize = puddleAsset
    ? {
        width: puddleAsset.metadata.meta.size.w * puddleAsset.imageScale * displayScale,
        height: puddleAsset.metadata.meta.size.h * puddleAsset.imageScale * displayScale,
      }
    : null;
  const puddleOffset = puddleAsset && puddleFrame
    ? frameOffset(puddleFrame, puddleAsset.imageScale, displayScale, 0)
    : null;
  const backgroundUri = backgroundSpritePath
    ? resolveSlimeRemoteSpriteUri(backgroundSpritePath, getApiBase())
    : "";
  const renderBackgroundLayer = (sizeStyle: { width: number; height: number }) =>
    backgroundUri ? (
      <FeatheredBackground backgroundUri={backgroundUri} sizeStyle={sizeStyle} />
    ) : null;

  if (itemSpritePath) {
    const uri = resolveSlimeRemoteSpriteUri(itemSpritePath, getApiBase());
    const size = 256 * displayScale;
    const itemSizeStyle = { width: size, height: size };
    const itemViewportStyle = { width: size, height: size + floorRise };
    return (
      <View
        style={[styles.viewport, itemViewportStyle]}
        accessible
        accessibilityRole="image"
        accessibilityLabel={accessibilityLabel ?? `${slimeColor} 슬라임 장착 소품 모습`}
        testID="slime-sprite"
      >
        {renderBackgroundLayer(itemSizeStyle)}
        {puddleAsset && puddlePackedSheetSize && puddleOffset ? (
          <Image
            source={imageSource(puddleAsset.image)}
            style={[styles.layer, styles.floorUnder, puddlePackedSheetSize, puddleOffset]}
            contentFit="fill"
            allowDownscaling={false}
            recyclingKey={`${playbackKey}:puddle-under-item`}
            transition={0}
            accessible={false}
          />
        ) : null}
        {staticFloor ? (
          <Image
            source={imageSource(staticFloor.image)}
            style={[styles.layer, styles.floorUnder, itemSizeStyle, { top: floorRise }]}
            contentFit="fill"
            allowDownscaling={false}
            recyclingKey={`${playbackKey}:floor-under-item`}
            transition={0}
            accessible={false}
          />
        ) : null}
        {equippedFloor === "trampoline" ? (
          <Image
            source={imageSource(TRAMPOLINE_FLOOR_SOURCE)}
            style={[styles.layer, styles.floorUnder, itemSizeStyle]}
            contentFit="fill"
            allowDownscaling={false}
            recyclingKey={`${playbackKey}:trampoline-under-item`}
            transition={0}
            accessible={false}
          />
        ) : null}
        <Image
          source={{ uri }}
          style={[styles.layer, styles.itemLayer, itemSizeStyle]}
          contentFit="contain"
          recyclingKey={`item:${uri}`}
          transition={0}
          accessible={false}
        />
      </View>
    );
  }

  return (
    <View
      style={[styles.viewport, viewport]}
      accessible
      accessibilityRole="image"
      accessibilityLabel={
        accessibilityLabel ?? `${slimeColor} 슬라임 ${resolution.action} 모습`
      }
      testID="slime-sprite"
    >
      {renderBackgroundLayer({ width: squareSourceSize, height: squareSourceSize })}
      {puddleAsset && puddlePackedSheetSize && puddleOffset ? (
        <Image
          source={imageSource(puddleAsset.image)}
          style={[styles.layer, styles.floorUnder, puddlePackedSheetSize, puddleOffset]}
          contentFit="fill"
          allowDownscaling={false}
          recyclingKey={`${playbackKey}:puddle`}
          transition={0}
          accessible={false}
        />
      ) : null}
      {staticFloor ? (
        <Image
          source={imageSource(staticFloor.image)}
          style={[
            styles.layer,
            styles.floorUnder,
            {
              width: frame.sourceSize.w * staticFloor.imageScale * displayScale,
              height: squareSourceSize,
              left: 0,
              top: floorRise,
            },
          ]}
          contentFit="fill"
          allowDownscaling={false}
          recyclingKey={`${playbackKey}:floor`}
          transition={0}
          accessible={false}
        />
      ) : null}
      <Image
        source={imageSource(resolution.sheet)}
        style={[styles.layer, packedSheetSize, offset]}
        contentFit="fill"
        allowDownscaling={false}
        recyclingKey={playbackKey}
        transition={0}
        accessible={false}
      />
      {resolvedWearables.map((wearable) => (
        // One shared sheet per option. The anchor track selects this frame's
        // source column and nudges it by the authored offset. Jump overlays sit on
        // a taller canvas, so `characterOffsetY` brings them back onto the
        // character viewport; grounded actions report zero.
        <Image
          key={wearable.key}
          source={imageSource(wearable.image)}
          style={[
            styles.layer,
            {
              width:
                wearable.frameSize.w * wearable.sheetFrameCount * wearable.imageScale * displayScale,
              height: wearable.frameSize.h * wearable.imageScale * displayScale,
              left:
                (-wearable.sourceFrame * wearable.frameSize.w + wearable.dx) *
                wearable.imageScale *
                displayScale,
              top: (wearable.dy - wearable.characterOffsetY) * wearable.imageScale * displayScale,
              zIndex: layers.spriteItem + wearable.zIndex,
            },
          ]}
          contentFit="fill"
          allowDownscaling={false}
          recyclingKey={`${playbackKey}:${wearable.key}:${wearable.sourceFrame}`}
          transition={0}
          accessible={false}
        />
      ))}
      {resolution.happyHeart ? (
        <Image
          source={imageSource(resolution.happyHeart.sheet)}
          style={[
            styles.layer,
            packedSheetSize,
            offset,
            { zIndex: layers.spriteItem + 100 },
          ]}
          contentFit="fill"
          allowDownscaling={false}
          recyclingKey={`${playbackKey}:happy-heart-top`}
          transition={0}
          accessible={false}
          testID="slime-happy-heart-layer"
        />
      ) : null}
    </View>
  );
}

export type { EquippedFloor, SlimeAction, SlimeColor, SlimeEvolution };

const styles = StyleSheet.create({
  viewport: {
    position: "relative",
    overflow: "hidden",
  },
  layer: {
    position: "absolute",
  },
  // Keep the background in the normal sibling stack. A negative z-index can
  // place it behind the clipped viewport on Android; render order keeps later
  // floor and character layers above it.
  backgroundLayer: { zIndex: layers.spriteFloor },
  floorUnder: { zIndex: layers.spriteFloor },
  itemLayer: { zIndex: layers.spriteItem },
});
