import { useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import { Image, type ImageProps } from "expo-image";
import MaskedView from "@react-native-masked-view/masked-view";
import { StyleSheet, View, type StyleProp, type ViewStyle } from "react-native";
import { layers, slimeUi } from "../../theme/tokens";
import { getApiBase } from "../../lib/api";
import {
  getSlimeFrame,
  resolveSlimeAsset,
  SLIME_SHARED_ASSETS,
  type SlimeAction,
  type SlimeColor,
  type SlimeEvolution,
  type EquippedFloor,
  type SlimeFrame,
} from "../../lib/slime-assets";
import { resolveSlimeRemoteSpriteUri } from "../../lib/slimes";
import {
  ensureRemoteSlimeWearable,
  resolveSlimeWearables,
  slimeWearableEntry,
  SLIME_WEARABLE_ROLES,
  type ResolvedSlimeWearable,
} from "../../lib/slime-wearables";
import {
  resolveSlimeBallPropAsset,
  resolveSlimePropAction,
  slimePropFrameOffset,
  type SlimePropAction,
} from "../../lib/slime-props";
import {
  cancelSlimeAnimationSchedule,
  scheduleSlimeAnimationInterval,
  scheduleSlimeAnimationTimeout,
  type SlimeAnimationScheduleHandle,
} from "../../lib/slime-animation-scheduler";
import { type SlimeSpriteProps } from "./slime-types";
import { styles } from "./slime-sprite.styles";

const DEFAULT_DISPLAY_SCALE = 1;
const TRAMPOLINE_FLOOR_SOURCE = require("../../assets/slimes/shared/trampoline-floor.png");
/**
 * Single alpha mask reproducing the previous four-edge feather product.
 * Generated by `scripts/generate-feather-mask.mjs`.
 */
const SCENE_BACKGROUND_FEATHER_MASK = require("../../assets/slimes/shared/scene-background-feather-mask.png");
type LocalImageSource = ImageProps["source"];

function normalizedDisplayScale(value: number | undefined): number {
  if (!Number.isFinite(value)) return DEFAULT_DISPLAY_SCALE;
  return Math.max(0.25, Math.round((value as number) * 16) / 16);
}

function imageSource(value: unknown): LocalImageSource {
  // The generated registry contains only literal Metro `require` values.
  // Keeping this cast at the render boundary prevents a remote URI from ever
  // entering the sprite player.
  return value as LocalImageSource;
}

function sourceSize(frame: SlimeFrame, imageScale: number, scale: number) {
  return {
    width: frame.sourceSize.w * imageScale * scale,
    height: frame.sourceSize.h * imageScale * scale,
  };
}

function frameOffset(
  frame: SlimeFrame,
  imageScale: number,
  scale: number,
  offsetY: number,
) {
  return {
    left: (frame.spriteSourceSize.x - frame.frame.x) * imageScale * scale,
    top:
      (frame.spriteSourceSize.y - frame.frame.y) * imageScale * scale + offsetY,
  };
}

/**
 * Scene background with feathered edges.
 *
 * This used to nest one `MaskedView` per edge, each with its own SVG gradient.
 * Nested masks multiply alpha, so an animated background paid four native masking
 * stages every frame, and a class list or the shop grid multiplied that by the
 * number of mounted backgrounds.
 *
 * The generated mask asset already contains that same alpha product
 * (`H(x) * V(y)`), so one masking stage now produces the identical result. The
 * feather is a fixed 1/16 of each axis, so stretching one mask to any square
 * container stays proportional and no per-size mask is needed.
 *
 * Regenerate the asset with `node scripts/generate-feather-mask.mjs`.
 */
export function FeatheredSceneBackground({
  spritePath,
  style,
}: {
  spritePath: string;
  style?: StyleProp<ViewStyle>;
}) {
  const backgroundUri = resolveSlimeRemoteSpriteUri(spritePath, getApiBase());
  return (
    <View
      pointerEvents="none"
      style={[styles.layer, styles.backgroundLayer, style]}
      accessible={false}
    >
      <MaskedView
        style={StyleSheet.absoluteFill}
        maskElement={
          <Image
            source={SCENE_BACKGROUND_FEATHER_MASK}
            style={StyleSheet.absoluteFill}
            // The mask is authored at 128px and carries a proportional feather, so
            // it must stretch to the container rather than preserve its ratio.
            contentFit="fill"
            transition={0}
            accessible={false}
          />
        }
      >
        <Image
          source={{ uri: backgroundUri }}
          style={StyleSheet.absoluteFill}
          contentFit="cover"
          recyclingKey={`background:${backgroundUri}`}
          transition={0}
          accessible={false}
        />
      </MaskedView>
    </View>
  );
}

/**
 * Native player for the imported official slime sheets.
 *
 * The PNGs are generated nearest-scaled at 4x. We therefore render their
 * physical dimensions exactly and crop the packed sheet inside a viewport;
 * no dynamic require, URL, interpolation, or CSS animation is involved.
 */
export function useSlimeSpriteModel({
  slimeColor,
  evolution = "base",
  action = "idle",
  equippedFloor = "none",
  displayScale: requestedDisplayScale = DEFAULT_DISPLAY_SCALE,
  accessibilityLabel,
  repeat = false,
  animate = true,
  itemSpritePath,
  propAction,
  backgroundSpritePath,
  expandSceneSurfaces = false,
  vehicleSpritePath,
  vehicleGroundedSpritePath,
  vehicleEffectSpritePaths,
  vehicleFrameCount = 1,
  vehicleGroundedFrameCount = 1,
  vehicleGroundedFrameDurationMs = 100,
  vehicleCanvasHeight = 64,
  vehicleCharacterOffsetY = 0,
  vehicleBobY,
  vehicleRiseY = 0,
  vehicleOffsetX = 0,
  wearables,
  drinkFlavor,
  growthStage,
  onComplete,
}: SlimeSpriteProps) {
  const displayScale = normalizedDisplayScale(requestedDisplayScale);
  const [remoteWearableRevision, setRemoteWearableRevision] = useState(0);
  const requestedPropAction = useMemo<SlimePropAction | null>(
    () =>
      propAction ??
      (action === "drink" && drinkFlavor
        ? {
            kind: "drink",
            itemKey: `drink:${drinkFlavor}`,
            flavor: drinkFlavor,
          }
        : null),
    [action, drinkFlavor, propAction],
  );
  const actionResolution = useMemo(
    () => resolveSlimePropAction(action, requestedPropAction, equippedFloor),
    [action, equippedFloor, requestedPropAction],
  );
  const resolution = useMemo(
    () =>
      resolveSlimeAsset({
        slimeColor,
        evolution,
        action: actionResolution.characterAction,
        equippedFloor,
        growthStage,
        equippedHeadwear: wearables?.headwear ?? null,
        drinkFlavor:
          actionResolution.prop?.kind === "drink"
            ? actionResolution.prop.flavor
            : drinkFlavor,
      }),
    [
      actionResolution.characterAction,
      drinkFlavor,
      equippedFloor,
      evolution,
      growthStage,
      actionResolution.prop,
      slimeColor,
      wearables?.headwear,
      remoteWearableRevision,
    ],
  );
  useEffect(() => {
    let cancelled = false;
    const requests = SLIME_WEARABLE_ROLES.flatMap((role) => {
      const option = wearables?.[role];
      const assetPath = wearables?.assetPaths?.[role];
      if (!option || !assetPath || slimeWearableEntry(role, option)) return [];
      return [ensureRemoteSlimeWearable(role, option, assetPath)];
    });
    if (requests.length === 0) return;
    void Promise.all(requests).then((loaded) => {
      if (!cancelled && loaded.some(Boolean)) {
        setRemoteWearableRevision((current) => current + 1);
      }
    });
    return () => {
      cancelled = true;
    };
  }, [
    wearables?.assetPaths?.blush,
    wearables?.assetPaths?.drink,
    wearables?.assetPaths?.eyewear,
    wearables?.assetPaths?.headwear,
    wearables?.blush,
    wearables?.drink,
    wearables?.eyewear,
    wearables?.headwear,
  ]);

  const ballAsset =
    actionResolution.prop?.kind === "ball"
      ? resolveSlimeBallPropAsset(actionResolution.prop.slug, slimeColor)
      : null;
  const playbackKey = `${resolution.key}:${actionResolution.wearableAction}:${resolution.equippedFloor}:${actionResolution.prop?.itemKey ?? "none"}`;
  const playbackFrameCount = ballAsset?.frameCount ?? resolution.frameCount;
  const playbackLoops = Boolean(ballAsset) || resolution.loop;
  const playbackIsOneShot = ballAsset ? false : resolution.oneShot;
  const [frameIndex, setFrameIndex] = useState(0);
  const completedPlaybackRef = useRef<string | null>(null);
  const onCompleteRef = useRef(onComplete);
  onCompleteRef.current = onComplete;

  const frame = getSlimeFrame(resolution, frameIndex);
  const staticFloor = resolution.staticFloor;
  // The complete ball action is beneath equipment; only the prop pixels are
  // repeated at the top. Legacy item images remain a replacement path for
  // unrelated static props.
  const resolvedWearables = useMemo(() => {
    if (itemSpritePath || resolution.composition.mode !== "composed") return [];
    const selection = { ...wearables, headwear: resolution.renderedHeadwear };
    return resolveSlimeWearables(
      selection,
      slimeColor,
      actionResolution.wearableAction,
      frameIndex,
      resolution.drinkFlavor,
    );
  }, [
    frameIndex,
    itemSpritePath,
    actionResolution.wearableAction,
    resolution.composition.mode,
    resolution.drinkFlavor,
    resolution.renderedHeadwear,
    remoteWearableRevision,
    slimeColor,
    wearables,
  ]);
  const equipmentWearables = resolvedWearables.filter(
    (wearable) => wearable.role !== "drink",
  );
  const propWearables = resolvedWearables.filter(
    (wearable) => wearable.role === "drink",
  );
  const floorRise = staticFloor
    ? (staticFloor.slimeFootY - staticFloor.surfaceY) *
      resolution.imageScale *
      displayScale
    : 0;
  // A vehicle lifts the slime on top of whatever the floor already contributed,
  // so the two offsets add instead of overriding each other.
  const vehicleRise =
    Math.max(0, Math.trunc(vehicleRiseY)) *
    resolution.imageScale *
    displayScale;
  const totalRise = floorRise + vehicleRise;
  const vehicleBob = vehicleBobY?.length
    ? Math.trunc(vehicleBobY[frameIndex % vehicleBobY.length] ?? 0)
    : 0;
  /**
   * Rider offset: seat height plus this frame's bob. Without the bob the slime
   * would hold still while its seat moves under it.
   *
   * Authored bob values use screen coordinates: negative is upward. Keep that
   * sign when adding bob to the already-negative seat lift.
   */
  const riderOffsetY =
    -vehicleRise + vehicleBob * resolution.imageScale * displayScale;
  const baseViewport = sourceSize(frame, resolution.imageScale, displayScale);
  const hasVehicleScene = Boolean(
    vehicleSpritePath ||
    vehicleGroundedSpritePath ||
    vehicleEffectSpritePaths?.length,
  );
  // Scene art owns more visual area than the 64px character cell. Detect it at
  // the render boundary so a new call site cannot silently fall back to the
  // legacy character-only viewport just because it forgot an opt-in prop.
  const hasExpandedSceneSurfaces = Boolean(
    hasVehicleScene ||
    backgroundSpritePath ||
    staticFloor ||
    equippedFloor === "water-puddle" ||
    equippedFloor === "trampoline" ||
    requestedPropAction ||
    expandSceneSurfaces,
  );
  const sceneScale = hasExpandedSceneSurfaces ? slimeUi.vehicleSceneScale : 1;
  const sceneWidth = baseViewport.width * sceneScale;
  const sceneHeight = baseViewport.height * sceneScale;
  const sceneInsetX = (sceneWidth - baseViewport.width) / 2;
  const sceneInsetY = (sceneHeight - baseViewport.height) / 2;
  const floorScale = hasExpandedSceneSurfaces ? slimeUi.vehicleFloorScale : 1;
  const floorWidth = baseViewport.width * floorScale;
  const floorHeight = baseViewport.height * floorScale;
  const floorInsetX = (sceneWidth - floorWidth) / 2;
  const packedSheetSize = {
    width:
      resolution.metadata.meta.size.w * resolution.imageScale * displayScale,
    height:
      resolution.metadata.meta.size.h * resolution.imageScale * displayScale,
  };
  const ballPackedSheetSize = ballAsset
    ? {
        width:
          ballAsset.columns *
          ballAsset.frameSize *
          ballAsset.imageScale *
          displayScale,
        height:
          Math.ceil(ballAsset.frameCount / ballAsset.columns) *
          ballAsset.frameSize *
          ballAsset.imageScale *
          displayScale,
      }
    : null;
  const ballOffset = ballAsset
    ? slimePropFrameOffset(frameIndex, ballAsset, displayScale)
    : null;
  const baseOffset = frameOffset(
    frame,
    resolution.imageScale,
    displayScale,
    riderOffsetY,
  );
  const expandedFloorTop = staticFloor
    ? sceneInsetY +
      staticFloor.slimeFootY * resolution.imageScale * displayScale -
      staticFloor.surfaceY * staticFloor.imageScale * displayScale * floorScale
    : 0;
  const viewport = {
    width: sceneWidth,
    height: Math.max(
      sceneHeight,
      sceneInsetY + baseViewport.height + totalRise,
      staticFloor ? expandedFloorTop + floorHeight : 0,
    ),
  };

  // Reset before React Native paints the new action. A normal effect lets the
  // previous action's frame index render once against the new sheet, which is
  // visible as a single-frame flash when feeding switches idle -> happy.
  useLayoutEffect(() => {
    setFrameIndex(0);
    completedPlaybackRef.current = null;
  }, [playbackKey]);

  useEffect(() => {
    if (!animate) return;
    const currentDuration = ballAsset
      ? ballAsset.durations[frameIndex % ballAsset.frameCount]
      : getSlimeFrame(resolution, frameIndex).duration;
    const handle = scheduleSlimeAnimationTimeout(
      Math.max(0, currentDuration),
      () => {
        const isLastFrame = frameIndex >= playbackFrameCount - 1;
        if (playbackIsOneShot && isLastFrame && !repeat) {
          if (completedPlaybackRef.current !== playbackKey) {
            completedPlaybackRef.current = playbackKey;
            onCompleteRef.current?.();
          }
          return;
        }

        setFrameIndex((current) =>
          playbackLoops || repeat
            ? (current + 1) % playbackFrameCount
            : Math.min(current + 1, playbackFrameCount - 1),
        );
      },
    );

    return () => cancelSlimeAnimationSchedule(handle);
  }, [
    animate,
    ballAsset,
    frameIndex,
    playbackFrameCount,
    playbackIsOneShot,
    playbackKey,
    playbackLoops,
    repeat,
    resolution,
  ]);

  const puddleAsset =
    equippedFloor === "water-puddle" ? SLIME_SHARED_ASSETS.sharedPuddle : null;
  const puddleFrame = puddleAsset
    ? getSlimeFrame({ metadata: puddleAsset.metadata }, frameIndex)
    : null;
  const puddlePackedSheetSize = puddleAsset
    ? {
        width:
          puddleAsset.metadata.meta.size.w *
          puddleAsset.imageScale *
          displayScale,
        height:
          puddleAsset.metadata.meta.size.h *
          puddleAsset.imageScale *
          displayScale,
      }
    : null;
  const puddleOffset =
    puddleAsset && puddleFrame
      ? frameOffset(puddleFrame, puddleAsset.imageScale, displayScale, 0)
      : null;
  const vehicleUri = vehicleSpritePath
    ? resolveSlimeRemoteSpriteUri(vehicleSpritePath, getApiBase())
    : "";
  const vehicleGroundedUri = vehicleGroundedSpritePath
    ? resolveSlimeRemoteSpriteUri(vehicleGroundedSpritePath, getApiBase())
    : "";
  const vehicleEffectUris = (vehicleEffectSpritePaths ?? []).map((path) =>
    resolveSlimeRemoteSpriteUri(path, getApiBase()),
  );
  /**
   * Vehicles ride the character's frame clock with matching authored durations,
   * so one index keeps a ride and its rider in step.
   */
  const vehicleFrames = Math.max(1, Math.trunc(vehicleFrameCount));
  const vehicleGroundedFrames = Math.max(
    1,
    Math.trunc(vehicleGroundedFrameCount),
  );
  /**
   * Wheels turn on their own clock. Sharing the character's variable idle timing
   * would make a constant-rate rotation speed up and slow down mid-loop.
   */
  const [groundedFrame, setGroundedFrame] = useState(0);
  useEffect(() => {
    if (!animate || !vehicleGroundedSpritePath || vehicleGroundedFrames <= 1)
      return;
    const period = Math.max(16, Math.trunc(vehicleGroundedFrameDurationMs));
    const handle: SlimeAnimationScheduleHandle = scheduleSlimeAnimationInterval(
      period,
      () => {
        setGroundedFrame((current) => (current + 1) % vehicleGroundedFrames);
      },
    );
    return () => cancelSlimeAnimationSchedule(handle);
  }, [
    animate,
    vehicleGroundedFrameDurationMs,
    vehicleGroundedFrames,
    vehicleGroundedSpritePath,
  ]);

  const vehicleCanvas = Math.max(64, Math.trunc(vehicleCanvasHeight));
  // Vehicle headroom sits above the grounded pose, so the offset is subtracted to
  // land the art on the fixed slime-foot baseline. Static floors align their own
  // surface to that same baseline; adding `floorRise` here would lower only the
  // vehicle and sink it into an otherwise correctly positioned floor.
  const vehicleTop =
    -Math.trunc(vehicleCharacterOffsetY) * resolution.imageScale * displayScale;
  const vehicleLeft =
    Math.trunc(vehicleOffsetX) * resolution.imageScale * displayScale;
  const vehicleViewportStyle = {
    width: slimeUi.vehicleFrameWidth * resolution.imageScale * displayScale,
    height: vehicleCanvas * resolution.imageScale * displayScale,
    left: sceneInsetX + vehicleLeft,
    top: sceneInsetY + vehicleTop,
  };
  const itemLayer = itemSpritePath
    ? (() => {
        const uri = resolveSlimeRemoteSpriteUri(itemSpritePath, getApiBase());
        const size = 256 * displayScale;
        const itemSizeStyle = { width: size, height: size };
        const itemInsetX = (sceneWidth - size) / 2;
        const itemInsetY = (sceneHeight - size) / 2;
        const itemViewportStyle = {
          width: sceneWidth,
          height: Math.max(
            sceneHeight,
            itemInsetY + size + floorRise,
            staticFloor ? expandedFloorTop + floorHeight : 0,
          ),
        };
        const insetItemStyle = {
          ...itemSizeStyle,
          left: itemInsetX,
          top: itemInsetY,
        };
        return {
          uri,
          size,
          itemSizeStyle,
          itemInsetX,
          itemInsetY,
          itemViewportStyle,
          insetItemStyle,
        } as const;
      })()
    : null;

  return {
    styles,
    viewport,
    resolution,
    sceneWidth,
    sceneHeight,
    puddleAsset,
    puddleFrame,
    puddlePackedSheetSize,
    puddleOffset,
    sourceSize,
    displayScale,
    sceneInsetX,
    sceneInsetY,
    imageSource,
    playbackKey,
    staticFloor,
    floorWidth,
    floorHeight,
    floorInsetX,
    expandedFloorTop,
    vehicleGroundedUri,
    vehicleViewportStyle,
    vehicleGroundedFrames,
    groundedFrame,
    ballAsset,
    ballPackedSheetSize,
    ballOffset,
    riderOffsetY,
    baseViewport,
    packedSheetSize,
    baseOffset,
    equipmentWearables,
    vehicleUri,
    vehicleFrames,
    frameIndex,
    vehicleEffectUris,
    propWearables,
    FeatheredSceneBackground,
    vehicleCanvas,
    itemLayer,
    backgroundSpritePath,
    accessibilityLabel,
    slimeColor,
    equippedFloor,
    TRAMPOLINE_FLOOR_SOURCE,
  } as const;
}

export type SlimeSpriteViewModel = ReturnType<typeof useSlimeSpriteModel>;
